from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class PageAssets: 


	# Click Rule Assets
	# 进入游戏 
	C_ENTER_GAME = RuleClick(roi=(558, 576, 158, 38), area=(558, 576, 158, 38), name="enter_game")

	# Image Rule Assets
	# 主界面 
	I_C_MAIN = RuleImage(
		roi=(905, 134, 48, 48),
		area=(600, 110, 500, 96),
		file="./tasks/components/page/res/check/c_main.png"
	)
	# 适龄提示 
	I_C_LOGIN = RuleImage(
		roi=(165, 565, 52, 69),
		area=(0, 539, 300, 121),
		file="./tasks/components/page/res/check/c_login.png"
	)
	# 町中节能模式 
	I_C_TOWN = RuleImage(
		roi=(1065, 32, 90, 98),
		area=(1020, 0, 180, 188),
		file="./tasks/components/page/res/check/c_town.png"
	)
	# 町中武馆斗技 
	I_C_DOJO = RuleImage(
		roi=(720, 254, 24, 53),
		area=(708, 242, 48, 77),
		file="./tasks/components/page/res/check/c_dojo.png"
	)
	# 探索界面妖标志 
	I_C_EXP = RuleImage(
		roi=(62, 642, 49, 41),
		area=(42, 622, 89, 81),
		file="./tasks/components/page/res/check/c_exp.png"
	)
	# 章节入口探索标志 
	I_C_EXP_MODAL = RuleImage(
		roi=(1064, 233, 62, 108),
		area=(1033, 202, 124, 170),
		file="./tasks/components/page/res/check/c_exp_modal.png"
	)
	# 商店街建筑 
	I_C_MARKET = RuleImage(
		roi=(258, 470, 58, 44),
		area=(229, 448, 116, 88),
		file="./tasks/components/page/res/check/c_market.png"
	)
	# 礼包屋标志 
	I_C_GIFT_SHOP = RuleImage(
		roi=(1139, 658, 50, 26),
		area=(1126, 645, 76, 52),
		file="./tasks/components/page/res/check/c_gift_shop.png"
	)
	# 召唤界面蓝票 
	I_C_SUMMON = RuleImage(
		roi=(597, 606, 64, 59),
		area=(567, 576, 124, 119),
		file="./tasks/components/page/res/check/c_summon.png"
	)
	# 结界突破界面 
	I_C_REALM_RAID = RuleImage(
		roi=(574, 76, 174, 37),
		area=(556, 58, 210, 73),
		file="./tasks/components/page/res/check/c_realm_raid.png"
	)
	# 闲庭设置 
	I_C_SLEEP = RuleImage(
		roi=(256, 36, 36, 36),
		area=(238, 18, 72, 72),
		file="./tasks/components/page/res/check/c_sleep.png"
	)
	# 英杰试炼源氏补给图标 
	I_C_MINAMOTO = RuleImage(
		roi=(60, 615, 46, 50),
		area=(37, 592, 92, 96),
		file="./tasks/components/page/res/check/c_minamoto.png"
	)
	# 地域鬼王集结图标 
	I_C_BOSS = RuleImage(
		roi=(35, 628, 86, 50),
		area=(10, 603, 136, 100),
		file="./tasks/components/page/res/check/c_boss.png"
	)
	# 契灵之境标题 
	I_C_FAIRYLAND = RuleImage(
		roi=(110, 25, 126, 34),
		area=(93, 8, 160, 68),
		file="./tasks/components/page/res/check/c_fairyland.png"
	)
	# 召唤页面退出 
	I_V_SUMMON_TO_MAIN = RuleImage(
		roi=(34, 9, 42, 41),
		area=(14, 0, 82, 81),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)
	# 探索章节入口退出 
	I_V_EXP_MODAL_TO_EXP = RuleImage(
		roi=(1031, 133, 32, 34),
		area=(1015, 117, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 探索界面返回主界面 
	I_V_EXP_TO_MAIN = RuleImage(
		roi=(30, 36, 53, 44),
		area=(4, 14, 106, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 商店街退出 
	I_V_MARKET_TO_MAIN = RuleImage(
		roi=(24, 36, 53, 44),
		area=(2, 14, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 商店退出到商店街 
	I_V_STORE_TO_MARKET = RuleImage(
		roi=(30, 16, 42, 41),
		area=(10, 0, 82, 81),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)
	# 英杰试炼退出 
	I_V_MINAMOTO_TO_EXP = RuleImage(
		roi=(20, 16, 42, 41),
		area=(0, 0, 82, 81),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)
	# 阴阳寮退出 
	I_V_GUILD_TO_MAIN = RuleImage(
		roi=(30, 18, 42, 41),
		area=(10, 0, 82, 81),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)
	# 结界突破退出 
	I_V_REALM_RAID_TO_EXP = RuleImage(
		roi=(1190, 116, 32, 34),
		area=(1174, 100, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 地域鬼王退出 
	I_V_BOSS_TO_EXP = RuleImage(
		roi=(45, 35, 53, 44),
		area=(23, 13, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 主界面探索灯笼 
	I_V_MAIN_TO_EXP = RuleImage(
		roi=(655, 102, 55, 87),
		area=(490, 58, 600, 174),
		file="./tasks/components/page/res/goto/v_main_to_exp.png"
	)
	# 第二十八章位置（在最底下的时候） 
	I_V_EXP_TO_CH28 = RuleImage(
		roi=(1058, 493, 189, 94),
		area=(1011, 446, 268, 188),
		file="./tasks/components/page/res/goto/v_exp_to_ch28.png"
	)
	# 主界面阴阳寮入口 
	I_V_MAIN_TO_GUILD = RuleImage(
		roi=(542, 602, 47, 53),
		area=(518, 576, 94, 106),
		file="./tasks/components/page/res/goto/v_main_to_guild.png"
	)
	# 主界面召唤灯笼 
	I_V_MAIN_TO_SUMMON = RuleImage(
		roi=(1081, 170, 35, 76),
		area=(1064, 132, 70, 152),
		file="./tasks/components/page/res/goto/v_main_to_summon.png"
	)
	# 主界面町中入口 
	I_V_MAIN_TO_TOWN = RuleImage(
		roi=(713, 250, 52, 40),
		area=(360, 230, 790, 90),
		file="./tasks/components/page/res/goto/v_main_to_town.png"
	)
	# 退出町中 
	I_V_TOWN_TO_MAIN = RuleImage(
		roi=(36, 47, 53, 44),
		area=(14, 25, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 町中武馆入口 
	I_V_TOWN_TO_DOJO = RuleImage(
		roi=(319, 343, 30, 124),
		area=(304, 328, 60, 154),
		file="./tasks/components/page/res/goto/v_town_to_dojo.png"
	)
	# 退出町中武馆 
	I_V_DOJO_TO_TOWN = RuleImage(
		roi=(34, 25, 53, 44),
		area=(12, 3, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 探索界面寮突破入口 
	I_V_EXP_TO_REALM_RAID = RuleImage(
		roi=(251, 635, 58, 52),
		area=(222, 609, 116, 104),
		file="./tasks/components/page/res/goto/v_exp_to_realm_raid.png"
	)
	# 退出闲庭 
	I_V_SLEEP_TO_MAIN = RuleImage(
		roi=(43, 36, 32, 34),
		area=(27, 20, 64, 66),
		file="./tasks/components/page/res/goto/v_sleep_to_main.png"
	)
	# 商店入口 
	I_V_MAIN_TO_STORE = RuleImage(
		roi=(643, 616, 68, 56),
		area=(609, 588, 136, 112),
		file="./tasks/components/page/res/goto/v_main_to_store.png"
	)
	# 英杰试炼入口 
	I_V_EXP_TO_MINAMOTO = RuleImage(
		roi=(837, 639, 60, 46),
		area=(814, 616, 106, 92),
		file="./tasks/components/page/res/goto/v_exp_to_minamoto.png"
	)
	# 地域鬼王入口 
	I_V_EXP_TO_BOSS = RuleImage(
		roi=(641, 638, 60, 47),
		area=(617, 614, 108, 95),
		file="./tasks/components/page/res/goto/v_exp_to_boss.png"
	)
	# 御灵入口 
	I_V_EXP_TO_GORYOU = RuleImage(
		roi=(353, 639, 51, 45),
		area=(331, 617, 95, 89),
		file="./tasks/components/page/res/goto/v_exp_to_goryou.png"
	)
	# 御灵退出 
	I_V_GORYOU_TO_EXP = RuleImage(
		roi=(7, 15, 53, 44),
		area=(0, 0, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 契灵之境入口 
	I_V_EXP_TO_FB = RuleImage(
		roi=(1040, 638, 50, 35),
		area=(1022, 620, 86, 71),
		file="./tasks/components/page/res/goto/v_exp_to_fb.png"
	)
	# 退出契灵之境 
	I_V_BF_TO_EXP = RuleImage(
		roi=(29, 18, 42, 41),
		area=(9, 0, 82, 81),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)


