from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class SubaccountsAssets: 

	# Click Rule Assets
	# 同区好友 
	C_SAME_REGION_FRIENDS = RuleClick(roi=(150, 85, 100, 55), area=(150, 85, 100, 55), name="same_region_friends")
	# 跨区好友 
	C_CROSS_REGION_FRIENDS = RuleClick(roi=(270, 85, 90, 55), area=(270, 85, 90, 55), name="cross_region_friends")

	# Image Rule Assets
	# 悬赏封印 
	I_QUEST = RuleImage(
		name="quest",
		roi=(235, 337, 44, 34),
		area=(100, 220, 320, 268),
		file="./tasks/subaccounts/res/quest/quest.png"
	)
	# 悬赏封印标题 
	I_QUEST_HEADER = RuleImage(
		name="quest_header",
		roi=(572, 62, 170, 38),
		area=(553, 43, 208, 76),
		file="./tasks/subaccounts/res/quest/quest_header.png"
	)
	# 悬赏邀请+号1（红色） 
	I_QUEST_PLUS_BUTTON_1 = RuleImage(
		name="quest_plus_button_1",
		roi=(143, 365, 34, 38),
		area=(125, 340, 70, 80),
		file="./tasks/subaccounts/res/quest/quest_plus_button.png"
	)
	# 悬赏邀请+号2（红色） 
	I_QUEST_PLUS_BUTTON_2 = RuleImage(
		name="quest_plus_button_2",
		roi=(143, 365, 34, 38),
		area=(430, 340, 70, 80),
		file="./tasks/subaccounts/res/quest/quest_plus_button.png"
	)
	# 悬赏邀请+号3（红色） 
	I_QUEST_PLUS_BUTTON_3 = RuleImage(
		name="quest_plus_button_3",
		roi=(143, 365, 34, 38),
		area=(730, 340, 70, 80),
		file="./tasks/subaccounts/res/quest/quest_plus_button.png"
	)
	# 跨区/灰 
	I_CROSS_REGION_DISABLED = RuleImage(
		name="cross_region_disabled",
		roi=(270, 102, 19, 34),
		area=(260, 92, 39, 54),
		file="./tasks/subaccounts/res/quest/cross_region_disabled.png"
	)
	# 跨区/亮 
	I_CROSS_REGION_ENABLE = RuleImage(
		name="cross_region_enable",
		roi=(268, 96, 21, 43),
		area=(258, 86, 41, 63),
		file="./tasks/subaccounts/res/quest/cross_region_enable.png"
	)
	# 好友头像 
	I_AVATAR = RuleImage(
		name="avatar",
		roi=(183, 218, 23, 21),
		area=(173, 208, 43, 41),
		file="./tasks/subaccounts/res/quest/avatar.png"
	)
	# 好友头像已选中 
	I_AVATAR_SELECTED = RuleImage(
		name="avatar_selected",
		roi=(184, 217, 21, 22),
		area=(174, 207, 41, 42),
		file="./tasks/subaccounts/res/quest/avatar_selected.png"
	)
	# 邀请 
	I_INVITE = RuleImage(
		name="invite",
		roi=(540, 561, 60, 29),
		area=(526, 547, 88, 57),
		file="./tasks/subaccounts/res/quest/invite.png"
	)
	# 关闭悬赏面板 
	I_CLOSE_QUEST_BOARD = RuleImage(
		name="close_quest_board",
		roi=(1162, 117, 32, 34),
		area=(1146, 101, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 勾协邀请 
	I_QUEST_JADE = RuleImage(
		name="quest_jade",
		roi=(836, 532, 42, 30),
		area=(821, 517, 72, 60),
		file="./tasks/subaccounts/res/quest/quest_jade.png"
	)
	# 体协邀请 
	I_QUEST_AP = RuleImage(
		name="quest_ap",
		roi=(1022, 523, 42, 40),
		area=(1002, 503, 82, 80),
		file="./tasks/subaccounts/res/quest/quest_ap.png"
	)
	# 狗粮协作邀请 
	I_QUEST_DOG = RuleImage(
		name="quest_dog",
		roi=(513, 527, 44, 42),
		area=(492, 506, 86, 84),
		file="./tasks/subaccounts/res/quest/quest_dog.png"
	)
	# 猫粮协作邀请 
	I_QUEST_CAT = RuleImage(
		name="quest_cat",
		roi=(207, 530, 56, 39),
		area=(187, 510, 96, 79),
		file="./tasks/subaccounts/res/quest/quest_cat.png"
	)
	# 接受悬赏邀请 
	I_QUEST_ACCEPT = RuleImage(
		name="quest_accept",
		roi=(825, 395, 55, 46),
		area=(802, 372, 101, 92),
		file="./tasks/subaccounts/res/quest/quest_accept.png"
	)
	#  
	I_QUEST_ACCEPT = RuleImage(
		name="quest_accept",
		roi=(825, 395, 55, 46),
		area=(802, 372, 101, 92),
		file="./tasks/subaccounts/res/quest/quest_accept.png"
	)
	# 拒绝悬赏邀请 
	I_QUEST_REJECT = RuleImage(
		name="quest_reject",
		roi=(826, 495, 53, 49),
		area=(802, 471, 101, 97),
		file="./tasks/subaccounts/res/quest/quest_reject.png"
	)
	# 关闭/无视悬赏邀请 
	I_QUEST_IGNORE = RuleImage(
		name="quest_ignore",
		roi=(764, 107, 40, 38),
		area=(745, 88, 78, 76),
		file="./tasks/subaccounts/res/quest/quest_ignore.png"
	)
	# 协作邀请现世标记位置 
	I_QUEST_VIRTUAL = RuleImage(
		name="quest_virtual",
		roi=(524, 159, 26, 29),
		area=(511, 144, 52, 58),
		file="./tasks/subaccounts/res/quest/quest_virtual.png"
	)
	# 现世共享+（紫色） 
	I_VIRTUAL_INVITE = RuleImage(
		name="virtual_invite",
		roi=(145, 364, 31, 41),
		area=(129, 348, 63, 73),
		file="./tasks/subaccounts/res/quest/virtual_invite.png"
	)
	# 关闭悬赏面板 
	I_CLOSE_QUEST_BOARD = RuleImage(
		name="close_quest_board",
		roi=(1162, 117, 32, 34),
		area=(1146, 101, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 取消邀请 
	I_CANCEL_INVITE = RuleImage(
		name="cancel_invite",
		roi=(269, 562, 57, 28),
		area=(255, 548, 85, 56),
		file="./tasks/subaccounts/res/quest/cancel_invite.png"
	)


