from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class SwitchSoulsAssets: 


	# Click Rule Assets
	# 切换队伍顶部 
	C_SS_TEAM_TOP = RuleClick(roi=(970, 148, 33, 34), area=(970, 148, 33, 34), name="ss_team_top")
	# 切换队伍中间 
	C_SS_TEAM_MID = RuleClick(roi=(970, 299, 33, 34), area=(970, 299, 33, 34), name="ss_team_mid")
	# 切换队伍底部 
	C_SS_TEAM_BOTTOM = RuleClick(roi=(970, 450, 33, 34), area=(970, 450, 33, 34), name="ss_team_bottom")

	# Image Rule Assets
	# 式神录幕间皮肤按钮 
	I_SHIKI_BOOK_CHECK = RuleImage(
		roi=(273, 11, 31, 26),
		area=(260, 0, 57, 52),
		file="./tasks/components/switch_souls/res/shiki_book_check.png"
	)
	# 确定更换御魂 
	I_SS_CONFIRM = RuleImage(
		roi=(672, 403, 172, 57),
		area=(644, 375, 228, 113),
		file="./tasks/battle/res/battle_fight_again_confirm.png"
	)
	# 预设分组1 
	I_SS_GROUP_1 = RuleImage(
		roi=(1091, 97, 8, 33),
		area=(1087, 93, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组2 
	I_SS_GROUP_2 = RuleImage(
		roi=(1091, 167, 8, 33),
		area=(1087, 163, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组3 
	I_SS_GROUP_3 = RuleImage(
		roi=(1091, 236, 8, 33),
		area=(1087, 232, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组4 
	I_SS_GROUP_4 = RuleImage(
		roi=(1091, 306, 8, 33),
		area=(1087, 302, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组5 
	I_SS_GROUP_5 = RuleImage(
		roi=(1091, 376, 8, 33),
		area=(1087, 372, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组6 
	I_SS_GROUP_6 = RuleImage(
		roi=(1091, 446, 8, 33),
		area=(1087, 442, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组7 
	I_SS_GROUP_7 = RuleImage(
		roi=(1091, 515, 8, 33),
		area=(1087, 511, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)
	# 预设分组8 
	I_SS_GROUP_8 = RuleImage(
		roi=(1091, 585, 8, 33),
		area=(1087, 581, 16, 41),
		file="./tasks/components/switch_souls/res/ss_group.png"
	)


	# Swipe Rule Assets
	# 向上滑动队伍预设 
	S_SW_TEAM_UP = RuleSwipe(
		roi_start=(766, 465, 0, 0),
		roi_end=(766, 164, 0, 0),
		name="sw_team_up"
	)


