from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class BattleAssets: 

	# Image Rule Assets
	# 战斗准备 
	I_BATTLE_READY = RuleImage(
		name="battle_ready",
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/components/battle/res/battle_ready.png"
	)
	# 战斗胜利图标 
	I_BATTLE_WIN = RuleImage(
		name="battle_win",
		roi=(411, 122, 172, 129),
		area=(325, 58, 344, 258),
		file="./tasks/components/battle/res/battle_win.png"
	)
	# 战斗失败图标 
	I_BATTLE_FAILED = RuleImage(
		name="battle_failed",
		roi=(409, 136, 125, 100),
		area=(359, 86, 225, 200),
		file="./tasks/components/battle/res/battle_failed.png"
	)
	# 探索战斗鬼火总量 
	I_BATTLE_CHECK = RuleImage(
		name="battle_check",
		roi=(557, 688, 28, 26),
		area=(544, 675, 54, 52),
		file="./tasks/components/battle/res/battle_check.png"
	)
	# 突破战斗退出 
	I_BATTLE_EXIT = RuleImage(
		name="battle_exit",
		roi=(21, 17, 35, 33),
		area=(4, 0, 70, 66),
		file="./tasks/components/battle/res/battle_exit.png"
	)
	# 退出战斗确认 
	I_BATTLE_EXIT_CONFIRM = RuleImage(
		name="battle_exit_confirm",
		roi=(679, 396, 124, 52),
		area=(653, 370, 176, 104),
		file="./tasks/components/widgets/res/buttons/b_confirm_narrow.png"
	)
	# 再次挑战 
	I_BATTLE_FIGHT_AGAIN = RuleImage(
		name="battle_fight_again",
		roi=(827, 476, 63, 72),
		area=(796, 440, 126, 144),
		file="./tasks/components/battle/res/battle_fight_again.png"
	)
	# 再次挑战确认 
	I_BATTLE_FIGHT_AGAIN_CONFIRM = RuleImage(
		name="battle_fight_again_confirm",
		roi=(672, 403, 172, 57),
		area=(586, 374, 344, 114),
		file="./tasks/components/widgets/res/buttons/b_confirm_wide.png"
	)
	# 战斗金币奖励 
	I_BATTLE_GOLD = RuleImage(
		name="battle_gold",
		roi=(266, 176, 101, 71),
		area=(230, 140, 840, 300),
		file="./tasks/components/battle/res/battle_gold.png"
	)
	# 手动 
	I_BATTLE_MANUAL = RuleImage(
		name="battle_manual",
		roi=(35, 647, 27, 28),
		area=(21, 633, 55, 56),
		file="./tasks/components/battle/res/battle_manual.png"
	)
	# 自动 
	I_BATTLE_AUTO = RuleImage(
		name="battle_auto",
		roi=(39, 647, 21, 29),
		area=(29, 637, 41, 49),
		file="./tasks/components/battle/res/battle_auto.png"
	)


	# Click Rule Assets
	# left 
	C_WIN_L = RuleClick(roi=(50, 100, 150, 200), area=(50, 100, 150, 200), name="win_l")
	# right 
	C_WIN_R = RuleClick(roi=(1150, 100, 100, 230), area=(1150, 100, 100, 230), name="win_r")
	# left 
	C_REWARD_1 = RuleClick(roi=(110, 130, 130, 300), area=(110, 130, 130, 300), name="reward_1")
	# right 
	C_REWARD_2 = RuleClick(roi=(1100, 130, 130, 300), area=(1100, 130, 130, 500), name="reward_2")


