from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class MainPageAssets: 

	# Image Rule Assets
	# 悬赏封印 
	I_QUEST = RuleImage(
		name="quest",
		roi=(235, 337, 44, 34),
		area=(100, 270, 320, 168),
		file="./tasks/main_page/res/quest/quest.png"
	)
	# 悬赏封印标题 
	I_QUEST_HEADER = RuleImage(
		name="quest_header",
		roi=(572, 62, 170, 38),
		area=(553, 43, 208, 76),
		file="./tasks/main_page/res/quest/quest_header.png"
	)
	# 悬赏邀请+ 
	I_QUEST_PLUS_BUTTON = RuleImage(
		name="quest_plus_button",
		roi=(143, 358, 37, 52),
		area=(125, 340, 1015, 88),
		file="./tasks/main_page/res/quest/quest_plus_button.png"
	)
	# 跨区/灰 
	I_CROSS_REGION = RuleImage(
		name="cross_region",
		roi=(267, 85, 102, 57),
		area=(239, 57, 158, 113),
		file="./tasks/main_page/res/quest/cross_region.png"
	)
	# 跨区/亮 
	I_CROSS_REGION_ENABLE = RuleImage(
		name="cross_region_enable",
		roi=(266, 81, 102, 63),
		area=(234, 49, 166, 127),
		file="./tasks/main_page/res/quest/cross_region_enable.png"
	)
	# 好友头像 
	I_QUEST_AVATAR = RuleImage(
		name="quest_avatar",
		roi=(176, 209, 29, 24),
		area=(150, 180, 580, 350),
		file="./tasks/main_page/res/quest/quest_avatar.png"
	)
	# 好友头像已选中 
	I_QUEST_AVATAR_SELECTED = RuleImage(
		name="quest_avatar_selected",
		roi=(178, 207, 29, 28),
		area=(150, 180, 580, 350),
		file="./tasks/main_page/res/quest/quest_avatar_selected.png"
	)
	# 邀请 
	I_INVITE = RuleImage(
		name="invite",
		roi=(503, 543, 132, 63),
		area=(471, 511, 196, 127),
		file="./tasks/main_page/res/quest/invite.png"
	)
	# 关闭悬赏面板 
	I_CLOSE_QUEST_BOARD = RuleImage(
		name="close_quest_board",
		roi=(1162, 117, 32, 34),
		area=(1146, 101, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 勾协邀请 
	I_QUEST_JADE = RuleImage(
		name="quest_jade",
		roi=(654, 459, 60, 50),
		area=(526, 420, 235, 135),
		file="./tasks/main_page/res/quest/quest_jade.png"
	)
	# 体协邀请 
	I_QUEST_AP = RuleImage(
		name="quest_ap",
		roi=(654, 460, 60, 47),
		area=(526, 420, 235, 135),
		file="./tasks/main_page/res/quest/quest_ap.png"
	)
	# 狗粮协作邀请 
	I_QUEST_DOG = RuleImage(
		name="quest_dog",
		roi=(204, 514, 64, 55),
		area=(526, 420, 235, 135),
		file="./tasks/main_page/res/quest/quest_dog.png"
	)
	# 猫粮协作邀请 
	I_QUEST_CAT = RuleImage(
		name="quest_cat",
		roi=(204, 515, 64, 54),
		area=(526, 420, 235, 135),
		file="./tasks/main_page/res/quest/quest_cat.png"
	)
	# 接受悬赏邀请 
	I_QUEST_ACCEPT = RuleImage(
		name="quest_accept",
		roi=(825, 395, 55, 46),
		area=(798, 372, 110, 92),
		file="./tasks/main_page/res/quest/quest_accept.png"
	)
	# 拒绝悬赏邀请 
	I_QUEST_REJECT = RuleImage(
		name="quest_reject",
		roi=(826, 495, 53, 49),
		area=(800, 470, 106, 98),
		file="./tasks/main_page/res/quest/quest_reject.png"
	)
	# 关闭/无视悬赏邀请 
	I_QUEST_IGNORE = RuleImage(
		name="quest_ignore",
		roi=(764, 107, 40, 38),
		area=(744, 88, 80, 76),
		file="./tasks/main_page/res/quest/quest_ignore.png"
	)
	# 协作邀请现世标记位置 
	I_QUEST_VIRTUAL = RuleImage(
		name="quest_virtual",
		roi=(524, 159, 26, 29),
		area=(511, 144, 52, 58),
		file="./tasks/main_page/res/quest/quest_virtual.png"
	)
	# 现世共享+ 
	I_VIRTUAL_INVITE = RuleImage(
		name="virtual_invite",
		roi=(444, 360, 38, 46),
		area=(125, 340, 1015, 88),
		file="./tasks/main_page/res/quest/virtual_invite.png"
	)

	# Swipe Rule Assets
	# 已有角色往左滑 
	S_REGION_TO_LEFT = RuleSwipe(
		roi_start=(800, 470, 60, 100),
		roi_end=(400, 470, 50, 100),
		name="region_to_left"
	)


