from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RegionalBossAssets: 

	# Image Rule Assets
	# 击杀数最多 
	I_KILL_RANK_CHECK = RuleImage(
		roi=(942, 126, 148, 38),
		area=(923, 107, 186, 76),
		file="./tasks/regional_boss/res/kill_rank_check.png"
	)
	# 筛选 
	I_BOSS_FILTER = RuleImage(
		roi=(1107, 37, 49, 48),
		area=(1083, 13, 97, 96),
		file="./tasks/regional_boss/res/boss_filter.png"
	)
	# 击杀数排名第一的鬼王 
	I_KILL_CHALLENGE_1 = RuleImage(
		roi=(1077, 224, 82, 76),
		area=(1039, 186, 158, 152),
		file="./tasks/regional_boss/res/challenge.png"
	)
	# 击杀数排名第二的鬼王 
	I_KILL_CHALLENGE_2 = RuleImage(
		roi=(1077, 378, 82, 76),
		area=(1039, 340, 158, 152),
		file="./tasks/regional_boss/res/challenge.png"
	)
	# 击杀数排名第三的鬼王 
	I_KILL_CHALLENGE_3 = RuleImage(
		roi=(1077, 532, 82, 76),
		area=(1039, 494, 158, 152),
		file="./tasks/regional_boss/res/challenge.png"
	)
	# 挑战 
	I_BOSS_FIGHT = RuleImage(
		roi=(1110, 508, 88, 41),
		area=(1090, 488, 128, 81),
		file="./tasks/regional_boss/res/fight.png"
	)
	# 退出boss挑战页面 
	I_BOSS_EXIT = RuleImage(
		roi=(1188, 23, 46, 46),
		area=(1165, 0, 92, 92),
		file="./tasks/general/res/buttons/b_red_x.png"
	)
	# 准备 
	I_BOSS_READY = RuleImage(
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/battle/res/battle_ready.png"
	)
	# 普通难度 
	I_REGULAR_HARDNESS = RuleImage(
		roi=(273, 118, 38, 36),
		area=(255, 100, 74, 72),
		file="./tasks/regional_boss/res/regular_hardness.png"
	)


