from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class SwitchAccountAssets: 

	# Click Rule Assets
	# 庭院头像 
	C_AVATAR = RuleClick(roi=(22, 39, 73, 59), area=(22, 39, 73, 59), name="avatar")
	# 区域按钮 
	C_REGION = RuleClick(roi=(556, 508, 152, 34), area=(556, 508, 152, 34), name="region")
	# 合区账号1 
	C_SUB_REGION_1 = RuleClick(roi=(120, 140, 100, 60), area=(120, 140, 100, 60), name="sub_region_1")
	# 合区账号2 
	C_SUB_REGION_2 = RuleClick(roi=(120, 255, 100, 60), area=(120, 255, 100, 60), name="sub_region_2")
	# 合区账号3 
	C_SUB_REGION_3 = RuleClick(roi=(120, 380, 100, 60), area=(120, 380, 100, 60), name="sub_region_3")
	# 登录时随机点击 
	C_LOGIN_RANDOM_CLICK = RuleClick(roi=(800, 150, 150, 200), area=(800, 150, 150, 200), name="login_random_click")

	# Image Rule Assets
	# 用户中心 
	I_USER_CENTER = RuleImage(
		name="user_center",
		roi=(221, 449, 59, 55),
		area=(193, 421, 115, 200),
		file="./tasks/components/switch_account/res/user_center.png"
	)
	# 切换账号 
	I_SWITCH_ACCOUNT = RuleImage(
		name="switch_account",
		roi=(937, 180, 135, 58),
		area=(908, 151, 193, 116),
		file="./tasks/components/switch_account/res/switch_account.png"
	)
	# 账号登录 
	I_LOGIN = RuleImage(
		name="login",
		roi=(383, 413, 514, 64),
		area=(351, 381, 578, 128),
		file="./tasks/components/switch_account/res/login.png"
	)
	# 苹果图标 
	I_APPLE_LOGO = RuleImage(
		name="apple_logo",
		roi=(511, 371, 58, 67),
		area=(482, 342, 116, 125),
		file="./tasks/components/switch_account/res/apple_logo.png"
	)
	# 选择区域 
	I_PICK_REGION = RuleImage(
		name="pick_region",
		roi=(500, 77, 271, 33),
		area=(484, 61, 303, 65),
		file="./tasks/components/switch_account/res/pick_region.png"
	)
	# 已有角色 
	I_OWN_CHARACTERS = RuleImage(
		name="own_characters",
		roi=(245, 417, 121, 29),
		area=(231, 403, 149, 57),
		file="./tasks/components/switch_account/res/own_characters.png"
	)
	# 展开已有账号区域 
	I_OPEN_REGIONS = RuleImage(
		name="open_regions",
		roi=(1040, 583, 20, 31),
		area=(1030, 573, 40, 51),
		file="./tasks/components/switch_account/res/open_regions.png"
	)

	# Image Rule Assets
	# 海外加速区 
	I_R_HAI_WAI_JIA_SU_QU = RuleImage(
		name="r_hai_wai_jia_su_qu",
		roi=(681, 492, 64, 47),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_hai_wai_jia_su_qu.png"
	)
	# 人间千年 
	I_R_REN_JIAN_QIAN_NIAN = RuleImage(
		name="r_ren_jian_qian_nian",
		roi=(473, 494, 73, 45),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_ren_jian_qian_nian.png"
	)
	# 猫川别馆 
	I_R_MAO_CHUAN_BIE_GUAN = RuleImage(
		name="r_mao_chuan_bie_guan",
		roi=(882, 492, 65, 48),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_mao_chuan_bie_guan.png"
	)
	# 永生之海 
	I_R_YONG_SHENG_ZHI_HAI = RuleImage(
		name="r_yong_sheng_zhi_hai",
		roi=(711, 493, 71, 47),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_yong_sheng_zhi_hai.png"
	)
	# 有龙则灵 
	I_R_YOU_LONG_ZE_LING = RuleImage(
		name="r_you_long_ze_ling",
		roi=(919, 488, 63, 51),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_you_long_ze_ling.png"
	)
	# 守山谣 
	I_R_SHOU_SHAN_YAO = RuleImage(
		name="r_shou_shan_yao",
		roi=(713, 493, 68, 44),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_shou_shan_yao.png"
	)
	# 魔卡绮遇 
	I_R_MO_KA_QI_YU = RuleImage(
		name="r_mo_ka_qi_yu",
		roi=(916, 492, 66, 47),
		area=(220, 450, 830, 120),
		file="./tasks/components/switch_account/res/regions/r_mo_ka_qi_yu.png"
	)

	# Swipe Rule Assets
	# 已有角色往左滑 
	S_REGION_TO_LEFT = RuleSwipe(
		roi_start=(800, 470, 60, 100),
		roi_end=(400, 470, 50, 100),
		name="region_to_left"
	)


