from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class GoryouRealmAssets: 


	# Click Rule Assets
	# 暗神龙 
	C_DARK_DIVINE_DRAGON = RuleClick(roi=(120, 150, 180, 470), area=(120, 150, 180, 470), name="Dark_Divine_Dragon")
	# 暗白蔵主 
	C_DARK_HAKUZOUSU = RuleClick(roi=(420, 150, 180, 470), area=(420, 150, 180, 470), name="Dark_Hakuzousu")
	# 暗黑豹 
	C_DARK_BLACK_PANTHER = RuleClick(roi=(700, 150, 180, 470), area=(700, 150, 180, 470), name="Dark_Black_Panther")
	# 暗孔雀 
	C_DARK_PEACOCK = RuleClick(roi=(120, 150, 180, 470), area=(120, 150, 180, 470), name="Dark_Peacock")
	# 一层 
	C_LV_1 = RuleClick(roi=(175, 170, 280, 70), area=(175, 170, 280, 70), name="lv_1")
	# 二层 
	C_LV_2 = RuleClick(roi=(175, 325, 280, 70), area=(175, 325, 280, 70), name="lv_2")
	# 三层 
	C_LV_3 = RuleClick(roi=(175, 485, 280, 70), area=(175, 485, 280, 70), name="lv_3")

	# Image Rule Assets
	# 御灵主页标记 
	I_GR_CHECK = RuleImage(
		roi=(81, 21, 128, 34),
		area=(64, 4, 162, 68),
		file="./tasks/goryou_realm/res/gr_check.png"
	)
	# 御灵挑战 
	I_GR_FIGHT = RuleImage(
		roi=(1109, 602, 74, 72),
		area=(1073, 566, 146, 144),
		file="./tasks/goryou_realm/res/gr_fight.png"
	)
	# 御灵三层 
	I_GR_LV_3 = RuleImage(
		roi=(288, 512, 65, 28),
		area=(274, 498, 93, 56),
		file="./tasks/goryou_realm/res/gr_lv_3.png"
	)
	#  
	I_GR_TEAM_LOCK = RuleImage(
		roi=(559, 563, 23, 30),
		area=(547, 551, 47, 54),
		file="./tasks/battle/res/battle_team_lock.png"
	)
	#  
	I_GR_TEAM_UNLOCK = RuleImage(
		roi=(562, 566, 17, 25),
		area=(554, 558, 33, 41),
		file="./tasks/battle/res/battle_team_unlock.png"
	)
	# 一层点亮 
	I_GR_LV_1_HIGHLIGHT = RuleImage(
		roi=(355, 188, 62, 36),
		area=(337, 170, 98, 72),
		file="./tasks/goryou_realm/res/gr_lv_highlight.png"
	)
	# 二层点亮 
	I_GR_LV_2_HIGHLIGHT = RuleImage(
		roi=(364, 347, 62, 36),
		area=(346, 329, 98, 72),
		file="./tasks/goryou_realm/res/gr_lv_highlight.png"
	)
	# 三层点亮 
	I_GR_LV_3_HIGHLIGHT = RuleImage(
		roi=(366, 505, 62, 36),
		area=(348, 487, 98, 72),
		file="./tasks/goryou_realm/res/gr_lv_highlight.png"
	)

	# Ocr Rule Assets
	# 御灵门票数量 
	O_GR_TICKET_COUNT = RuleOcr(
		roi=(930, 25, 82, 26),
		area=(930, 25, 82, 26),
		keyword="",
		name="gr_ticket_count"
	)


