from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class GoryouRealmAssets: 

	# Image Rule Assets
	# 御灵主页标记 
	I_GR_CHECK = RuleImage(
		roi=(81, 21, 128, 34),
		area=(64, 4, 162, 68),
		file="./tasks/goryou_realm/res/gr_check.png"
	)
	# 御灵挑战 
	I_GR_FIGHT = RuleImage(
		roi=(1109, 602, 74, 72),
		area=(1073, 566, 146, 144),
		file="./tasks/goryou_realm/res/gr_fight.png"
	)
	# 御灵三层 
	I_GR_LV_3 = RuleImage(
		roi=(288, 512, 65, 28),
		area=(274, 498, 93, 56),
		file="./tasks/goryou_realm/res/gr_lv_3.png"
	)
	#  
	I_GR_TEAM_LOCK = RuleImage(
		roi=(559, 563, 23, 30),
		area=(547, 551, 47, 54),
		file="./tasks/battle/res/battle_team_lock.png"
	)
	#  
	I_GR_TEAM_UNLOCK = RuleImage(
		roi=(562, 566, 17, 25),
		area=(554, 558, 33, 41),
		file="./tasks/battle/res/battle_team_unlock.png"
	)


