from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RiftsShadowsAssets: 

	# Click Rule Assets
	# 神龙暗域 
	C_DARK_DIVINE_DRAGON_SHADOW = RuleClick(roi=(105, 175, 195, 365), area=(105, 175, 195, 365), name="dark_divine_dragon_shadow")
	# 孔雀暗域 
	C_DARK_PEACOCK_SHADOW = RuleClick(roi=(410, 130, 170, 355), area=(410, 130, 170, 355), name="dark_peacock_shadow")
	# 白藏主暗域 
	C_DARK_HAKUZOUSU_SHADOW = RuleClick(roi=(700, 155, 190, 360), area=(700, 155, 190, 360), name="dark_hakuzousu_shadow")
	# 黑豹暗域 
	C_DARK_BLACK_PANTHER_SHADOW = RuleClick(roi=(1030, 130, 170, 355), area=(1030, 130, 170, 355), name="dark_black_panther_shadow")
	# 暗域小地图 
	C_RS_MINI_MAP = RuleClick(roi=(1070, 65, 140, 56), area=(1070, 65, 140, 56), name="rs_mini_map")

	# Image Rule Assets
	# 阴阳寮内狭间入口 
	I_RS_GUILD_ENT = RuleImage(
		name="rs_guild_ent",
		roi=(34, 257, 81, 21),
		area=(10, 150, 190, 400),
		file="./tasks/rifts_shadows/res/rs_guild_ent.png"
	)
	# 狭间暗域主页 
	I_C_RIFTS_SHADOW = RuleImage(
		name="c_rifts_shadow",
		roi=(101, 24, 127, 33),
		area=(85, 8, 159, 65),
		file="./tasks/rifts_shadows/res/c_rifts_shadow.png"
	)
	# 挑战 
	I_RS_BATTLE = RuleImage(
		name="rs_battle",
		roi=(1121, 612, 73, 37),
		area=(1103, 594, 109, 73),
		file="./tasks/rifts_shadows/res/rs_battle.png"
	)
	# 暗域式神录入口 
	I_RS_SHIKI_BOOK_ENT = RuleImage(
		name="rs_shiki_book_ent",
		roi=(1201, 468, 46, 39),
		area=(1181, 448, 86, 79),
		file="./tasks/rifts_shadows/res/rs_shiki_book_ent.png"
	)
	# 暗域攻打标记 
	I_RS_ATTACK = RuleImage(
		name="rs_attack",
		roi=(1140, 591, 81, 74),
		area=(1103, 554, 155, 148),
		file="./tasks/rifts_shadows/res/rs_attack.png"
	)
	# 暗域首领（大地图里） 
	I_RS_DEMON_LEADER = RuleImage(
		name="rs_demon_leader",
		roi=(1006, 87, 37, 43),
		area=(988, 69, 73, 79),
		file="./tasks/rifts_shadows/res/rs_demon_leader.png"
	)
	# 暗域副将左（大地图里） 
	I_RS_DEMON_DEPUTY_L = RuleImage(
		name="rs_demon_deputy_l",
		roi=(918, 195, 35, 43),
		area=(900, 177, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域副将右（大地图里） 
	I_RS_DEMON_DEPUTY_R = RuleImage(
		name="rs_demon_deputy_r",
		roi=(1109, 195, 35, 43),
		area=(1091, 177, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域精英左（大地图里） 
	I_RS_DEMON_ELITE_L = RuleImage(
		name="rs_demon_elite_l",
		roi=(893, 314, 35, 43),
		area=(875, 296, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域精英中（大地图里） 
	I_RS_DEMON_ELITE_M = RuleImage(
		name="rs_demon_elite_m",
		roi=(1004, 314, 35, 43),
		area=(986, 296, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域精英右（大地图里） 
	I_RS_DEMON_ELITE_R = RuleImage(
		name="rs_demon_elite_r",
		roi=(1120, 314, 35, 43),
		area=(1102, 296, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 挑战页面首领标记 
	I_RS_C_LEADER = RuleImage(
		name="rs_c_leader",
		roi=(410, 146, 27, 57),
		area=(396, 132, 55, 85),
		file="./tasks/rifts_shadows/res/rs_c_leader.png"
	)
	# 挑战页面副将标记 
	I_RS_C_DEPUTY = RuleImage(
		name="rs_c_deputy",
		roi=(411, 147, 26, 56),
		area=(398, 134, 52, 82),
		file="./tasks/rifts_shadows/res/rs_c_deputy.png"
	)
	# 挑战页面精英标记 
	I_RS_C_ELITE = RuleImage(
		name="rs_c_elite",
		roi=(410, 146, 26, 57),
		area=(397, 133, 52, 83),
		file="./tasks/rifts_shadows/res/rs_c_elite.png"
	)
	# 关闭挑战页面 
	I_RS_BATTLE_PAGE_CLOSE = RuleImage(
		name="rs_battle_page_close",
		roi=(1001, 95, 32, 34),
		area=(985, 79, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 准备 
	I_RS_BATTLE_READY = RuleImage(
		name="rs_battle_ready",
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/components/battle/res/battle_ready.png"
	)
	# 退出战斗 
	I_RS_BATTLE_EXIT = RuleImage(
		name="rs_battle_exit",
		roi=(23, 20, 30, 30),
		area=(8, 5, 60, 60),
		file="./tasks/components/widgets/res/buttons/b_return_u.png"
	)
	# 退出战斗确定 
	I_RS_BATTLE_EXIT_CONFIRM = RuleImage(
		name="rs_battle_exit_confirm",
		roi=(679, 396, 124, 52),
		area=(653, 370, 176, 104),
		file="./tasks/components/widgets/res/buttons/b_confirm_narrow.png"
	)
	# 前往 
	I_RS_HEAD_FOR = RuleImage(
		name="rs_head_for",
		roi=(1125, 614, 69, 34),
		area=(1108, 597, 103, 68),
		file="./tasks/rifts_shadows/res/rs_head_for.png"
	)
	# 前往确认 
	I_RS_HEAD_FOR_CONFIRM = RuleImage(
		name="rs_head_for_confirm",
		roi=(672, 403, 172, 57),
		area=(644, 375, 228, 113),
		file="./tasks/components/widgets/res/buttons/b_confirm_wide.png"
	)

	# Ocr Rule Assets
	# 最佳成绩 
	O_RS_BATTLE_SCORE = RuleOcr(
		roi=(70, 113, 260, 43),
		area=(70, 113, 260, 43),
		keyword="",
		name="rs_battle_score"
	)


