from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RiftsShadowsAssets: 

	# Image Rule Assets
	# 首领（战报里） 
	I_T_LEADER = RuleImage(
		name="t_leader",
		roi=(678, 149, 79, 80),
		area=(678, 149, 79, 80),
		file=""
	)
	# 副将左（战报里） 
	I_T_DEPUTY_L = RuleImage(
		name="t_deputy_l",
		roi=(530, 290, 80, 82),
		area=(530, 290, 80, 82),
		file=""
	)
	# 副将右（战报里） 
	I_T_DEPUTY_R = RuleImage(
		name="t_deputy_r",
		roi=(842, 290, 80, 82),
		area=(842, 290, 80, 82),
		file=""
	)
	# 精英左（战报里） 
	I_T_ELITE_L = RuleImage(
		name="t_elite_l",
		roi=(440, 413, 80, 81),
		area=(440, 413, 80, 81),
		file=""
	)
	# 精英中（战报里） 
	I_T_ELITE_M = RuleImage(
		name="t_elite_m",
		roi=(680, 413, 80, 81),
		area=(680, 413, 80, 81),
		file=""
	)
	# 精英右（战报里） 
	I_T_ELITE_R = RuleImage(
		name="t_elite_r",
		roi=(924, 413, 80, 81),
		area=(924, 413, 80, 81),
		file=""
	)

	# Click Rule Assets
	# 神龙暗域 
	C_DARK_DIVINE_DRAGON_SHADOW = RuleClick(roi=(105, 175, 195, 365), area=(105, 175, 195, 365), name="dark_divine_dragon_shadow")
	# 孔雀暗域 
	C_DARK_PEACOCK_SHADOW = RuleClick(roi=(410, 130, 170, 355), area=(410, 130, 170, 355), name="dark_peacock_shadow")
	# 白藏主暗域 
	C_DARK_HAKUZOUSU_SHADOW = RuleClick(roi=(700, 155, 190, 360), area=(700, 155, 190, 360), name="dark_hakuzousu_shadow")
	# 黑豹暗域 
	C_DARK_BLACK_PANTHER_SHADOW = RuleClick(roi=(1030, 130, 170, 355), area=(1030, 130, 170, 355), name="dark_black_panther_shadow")
	# 暗域小地图 
	C_RS_MINI_MAP = RuleClick(roi=(1070, 65, 140, 56), area=(1070, 65, 140, 56), name="rs_mini_map")
	# 首领（战报里） 
	C_R_LEADER = RuleClick(roi=(690, 155, 60, 60), area=(690, 155, 60, 60), name="r_leader")
	# 精英左（战报里） 
	C_R_DEPUTY_L = RuleClick(roi=(540, 300, 60, 60), area=(540, 300, 60, 60), name="r_deputy_l")
	# 精英右（战报里） 
	C_R_DEPUTY_R = RuleClick(roi=(850, 300, 60, 60), area=(850, 300, 60, 60), name="r_deputy_r")
	# 精英左（战报里） 
	C_R_ELITE_L = RuleClick(roi=(450, 420, 60, 60), area=(450, 420, 60, 60), name="r_elite_l")
	# 精英中（战报里） 
	C_R_ELITE_M = RuleClick(roi=(690, 420, 60, 60), area=(690, 420, 60, 60), name="r_elite_m")
	# 精英右（战报里） 
	C_R_ELITE_R = RuleClick(roi=(930, 420, 60, 60), area=(930, 420, 60, 60), name="r_elite_r")

	# Image Rule Assets
	# 阴阳寮内狭间入口 
	I_RS_GUILD_ENT = RuleImage(
		name="rs_guild_ent",
		roi=(34, 257, 81, 21),
		area=(10, 150, 190, 400),
		file="./tasks/rifts_shadows/res/rs_guild_ent.png"
	)
	# 狭间暗域主页 
	I_C_RIFTS_SHADOW = RuleImage(
		name="c_rifts_shadow",
		roi=(101, 24, 127, 33),
		area=(85, 8, 159, 65),
		file="./tasks/rifts_shadows/res/c_rifts_shadow.png"
	)
	# 挑战 
	I_RS_BATTLE = RuleImage(
		name="rs_battle",
		roi=(1121, 612, 73, 37),
		area=(1103, 594, 109, 73),
		file="./tasks/rifts_shadows/res/rs_battle.png"
	)
	# 暗域式神录入口 
	I_RS_SHIKI_BOOK_ENT = RuleImage(
		name="rs_shiki_book_ent",
		roi=(1201, 468, 46, 39),
		area=(1181, 448, 86, 79),
		file="./tasks/rifts_shadows/res/rs_shiki_book_ent.png"
	)
	# 暗域攻打标记 
	I_RS_ATTACK = RuleImage(
		name="rs_attack",
		roi=(1140, 591, 81, 74),
		area=(1103, 554, 155, 148),
		file="./tasks/rifts_shadows/res/rs_attack.png"
	)
	# 暗域首领（大地图里） 
	I_RS_DEMON_LEADER = RuleImage(
		name="rs_demon_leader",
		roi=(1006, 87, 37, 43),
		area=(988, 69, 73, 79),
		file="./tasks/rifts_shadows/res/rs_demon_leader.png"
	)
	# 暗域副将左（大地图里） 
	I_RS_DEMON_DEPUTY_L = RuleImage(
		name="rs_demon_deputy_l",
		roi=(918, 195, 35, 43),
		area=(900, 177, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域副将右（大地图里） 
	I_RS_DEMON_DEPUTY_R = RuleImage(
		name="rs_demon_deputy_r",
		roi=(1109, 195, 35, 43),
		area=(1091, 177, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域精英左（大地图里） 
	I_RS_DEMON_ELITE_L = RuleImage(
		name="rs_demon_elite_l",
		roi=(893, 314, 35, 43),
		area=(875, 296, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域精英中（大地图里） 
	I_RS_DEMON_ELITE_M = RuleImage(
		name="rs_demon_elite_m",
		roi=(1004, 314, 35, 43),
		area=(986, 296, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 暗域精英右（大地图里） 
	I_RS_DEMON_ELITE_R = RuleImage(
		name="rs_demon_elite_r",
		roi=(1120, 314, 35, 43),
		area=(1102, 296, 71, 79),
		file="./tasks/rifts_shadows/res/rs_demon_elite.png"
	)
	# 挑战页面首领标记 
	I_RS_C_LEADER = RuleImage(
		name="rs_c_leader",
		roi=(410, 146, 27, 57),
		area=(396, 132, 55, 85),
		file="./tasks/rifts_shadows/res/rs_c_leader.png"
	)
	# 挑战页面副将标记 
	I_RS_C_DEPUTY = RuleImage(
		name="rs_c_deputy",
		roi=(411, 147, 26, 56),
		area=(398, 134, 52, 82),
		file="./tasks/rifts_shadows/res/rs_c_deputy.png"
	)
	# 挑战页面精英标记 
	I_RS_C_ELITE = RuleImage(
		name="rs_c_elite",
		roi=(410, 146, 26, 57),
		area=(397, 133, 52, 83),
		file="./tasks/rifts_shadows/res/rs_c_elite.png"
	)
	# 关闭挑战页面 
	I_RS_BATTLE_PAGE_CLOSE = RuleImage(
		name="rs_battle_page_close",
		roi=(1001, 95, 32, 34),
		area=(985, 79, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 准备 
	I_RS_BATTLE_READY = RuleImage(
		name="rs_battle_ready",
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/components/battle/res/battle_ready.png"
	)
	# 退出战斗 
	I_RS_BATTLE_EXIT = RuleImage(
		name="rs_battle_exit",
		roi=(23, 20, 30, 30),
		area=(8, 5, 60, 60),
		file="./tasks/components/widgets/res/buttons/b_return_u.png"
	)
	# 退出战斗确定 
	I_RS_BATTLE_EXIT_CONFIRM = RuleImage(
		name="rs_battle_exit_confirm",
		roi=(679, 396, 124, 52),
		area=(653, 370, 176, 104),
		file="./tasks/components/widgets/res/buttons/b_confirm_narrow.png"
	)
	# 前往 
	I_RS_HEAD_FOR = RuleImage(
		name="rs_head_for",
		roi=(1125, 614, 69, 34),
		area=(1108, 597, 103, 68),
		file="./tasks/rifts_shadows/res/rs_head_for.png"
	)
	# 前往确认 
	I_RS_HEAD_FOR_CONFIRM = RuleImage(
		name="rs_head_for_confirm",
		roi=(672, 403, 172, 57),
		area=(644, 375, 228, 113),
		file="./tasks/components/widgets/res/buttons/b_confirm_wide.png"
	)
	# 怪物分布 
	I_RS_DEMON_DIST = RuleImage(
		name="rs_demon_dist",
		roi=(311, 152, 160, 40),
		area=(291, 132, 200, 80),
		file="./tasks/rifts_shadows/res/rs_demon_dist.png"
	)
	# 战报 
	I_RS_BATTLE_REPORT = RuleImage(
		name="rs_battle_report",
		roi=(1202, 377, 38, 27),
		area=(1188, 363, 66, 55),
		file="./tasks/rifts_shadows/res/rs_battle_report.png"
	)
	# 神龙暗域（战报页面） 
	I_T_DDD = RuleImage(
		name="t_ddd",
		roi=(142, 182, 30, 18),
		area=(133, 173, 48, 36),
		file="./tasks/rifts_shadows/res/t_ddd.png"
	)
	# 白藏主暗域（战报页面） 
	I_T_DH = RuleImage(
		name="t_dh",
		roi=(143, 437, 38, 29),
		area=(129, 423, 66, 57),
		file="./tasks/rifts_shadows/res/t_dh.png"
	)
	# 孔雀暗域（战报页面） 
	I_T_DP = RuleImage(
		name="t_dp",
		roi=(138, 287, 37, 23),
		area=(126, 275, 61, 47),
		file="./tasks/rifts_shadows/res/t_dp.png"
	)
	# 黑豹暗域（战报页面） 
	I_T_DBP = RuleImage(
		name="t_dbp",
		roi=(149, 569, 40, 30),
		area=(134, 554, 70, 60),
		file="./tasks/rifts_shadows/res/t_dbp.png"
	)
	# 怪物40%血条（战报页面） 
	I_DEMON_LIFE = RuleImage(
		name="demon_life",
		roi=(445, 489, 30, 3),
		area=(443, 487, 34, 7),
		file="./tasks/rifts_shadows/res/demon_life.png"
	)
	# 退出狭间 
	I_RS_EXIT = RuleImage(
		name="rs_exit",
		roi=(24, 36, 53, 44),
		area=(2, 14, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)

	# Ocr Rule Assets
	# 最佳成绩 
	O_RS_BATTLE_SCORE = RuleOcr(
		roi=(70, 113, 260, 43),
		area=(70, 113, 260, 43),
		keyword="",
		name="rs_battle_score"
	)


