from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class DailyRoutineAssets: 


	# Click Rule Assets
	# 退出花合战 
	C_EXIT_HUAHE = RuleClick(roi=(19, 15, 55, 48), area=(19, 15, 55, 48), name="exit_huahe")

	# Image Rule Assets
	# 好友 
	I_FRIENDS = RuleImage(
		roi=(889, 626, 42, 46),
		area=(868, 605, 84, 88),
		file="./tasks/daily_routine/res/friends/friends.png"
	)
	# 好友标题 
	I_FRIEND_HEADER = RuleImage(
		roi=(586, 48, 145, 36),
		area=(568, 30, 181, 72),
		file="./tasks/daily_routine/res/friends/friend_header.png"
	)
	# 友情点/灰 
	I_FRIEND_POINTS = RuleImage(
		roi=(151, 643, 30, 38),
		area=(136, 628, 60, 68),
		file="./tasks/daily_routine/res/friends/friend_points.png"
	)
	# 友情点/亮 
	I_FRIEND_POINTS_ENABLE = RuleImage(
		roi=(128, 633, 60, 51),
		area=(102, 607, 112, 103),
		file="./tasks/daily_routine/res/friends/friend_points_enable.png"
	)
	# 跨区好友 
	I_CROSS_REGION_FRIENDS = RuleImage(
		roi=(240, 582, 99, 22),
		area=(229, 571, 121, 44),
		file="./tasks/daily_routine/res/friends/cross_region_friends.png"
	)
	# 一键收取 
	I_GET_ALL_FRIEND_POINTS = RuleImage(
		roi=(50, 541, 136, 44),
		area=(28, 519, 180, 88),
		file="./tasks/daily_routine/res/friends/get_all_friend_points.png"
	)
	# 好友羁绊提升关闭 
	I_FRIEND_LEVEL_UP_CLOSE = RuleImage(
		roi=(1161, 97, 32, 34),
		area=(1115, 49, 92, 92),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 退出好友 
	I_FRIENDS_EXIT = RuleImage(
		roi=(1163, 98, 32, 34),
		area=(1147, 82, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)

	# Image Rule Assets
	# 商店礼包屋入口 
	I_STORE_PACK = RuleImage(
		roi=(1140, 647, 62, 38),
		area=(1109, 628, 124, 76),
		file="./tasks/daily_routine/res/store/store_pack.png"
	)
	# 商店礼包推荐灯笼 
	I_STORE_REC = RuleImage(
		roi=(1195, 194, 28, 58),
		area=(1172, 50, 70, 350),
		file="./tasks/daily_routine/res/store/store_rec.png"
	)
	# 商店每日签到奖励 
	I_STORE_DAILY_REWARD = RuleImage(
		roi=(251, 164, 280, 103),
		area=(111, 112, 560, 206),
		file="./tasks/daily_routine/res/store/store_daily_reward.png"
	)
	# 商店礼包屋退出 
	I_STORE_EXIT = RuleImage(
		roi=(16, 7, 44, 40),
		area=(0, 0, 88, 80),
		file="./tasks/daily_routine/res/store/store_exit.png"
	)
	# 签到 
	I_SIGN = RuleImage(
		roi=(253, 509, 24, 20),
		area=(243, 499, 44, 40),
		file="./tasks/daily_routine/res/sign.png"
	)
	# 每日一签 
	I_DAILY_SIGN = RuleImage(
		roi=(597, 165, 87, 194),
		area=(553, 121, 175, 282),
		file="./tasks/daily_routine/res/daily_sign.png"
	)
	# 签到页面纸人 
	I_SIGN_DOLL = RuleImage(
		roi=(843, 538, 39, 120),
		area=(823, 518, 79, 160),
		file="./tasks/daily_routine/res/sign_doll.png"
	)
	# 关闭每日签到 
	I_CLOSE_DAILY_SIGN = RuleImage(
		roi=(855, 91, 32, 34),
		area=(839, 75, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 每日勾玉领取 
	I_DAILY_JADE = RuleImage(
		roi=(734, 482, 31, 34),
		area=(718, 466, 63, 66),
		file="./tasks/daily_routine/res/daily_jade.png"
	)
	# 每日寿司 
	I_DAILY_AP = RuleImage(
		roi=(737, 489, 26, 28),
		area=(724, 476, 52, 54),
		file="./tasks/daily_routine/res/daily_ap.png"
	)
	# 寮礼包 
	I_GUILD_PACK = RuleImage(
		roi=(246, 502, 34, 34),
		area=(229, 485, 68, 68),
		file="./tasks/daily_routine/res/guild_pack.png"
	)
	# 花合战 
	I_HUAHE = RuleImage(
		roi=(782, 614, 46, 44),
		area=(760, 592, 90, 88),
		file="./tasks/daily_routine/res/huahe.png"
	)
	# 全部领取花合战 
	I_GET_ALL_HUAHE = RuleImage(
		roi=(912, 604, 57, 55),
		area=(884, 576, 113, 111),
		file="./tasks/daily_routine/res/get_all_huahe.png"
	)
	# 每日御魂觉醒加成包 
	I_DAILY_BUFF = RuleImage(
		roi=(251, 502, 27, 33),
		area=(237, 488, 55, 61),
		file="./tasks/daily_routine/res/daily_buff.png"
	)
	# 商店礼包推荐 
	I_SHOP_PACK = RuleImage(
		roi=(252, 497, 32, 39),
		area=(250, 500, 60, 70),
		file="./tasks/daily_routine/res/shop_pack.png"
	)
	# 关闭商店礼包推荐 
	I_SHOP_PACK_CLOSE = RuleImage(
		roi=(1048, 132, 32, 34),
		area=(1032, 116, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)

	# Image Rule Assets
	# 邮件 
	I_MAIL = RuleImage(
		roi=(248, 506, 40, 20),
		area=(238, 496, 60, 40),
		file="./tasks/daily_routine/res/mail/mail.png"
	)
	# 邮件入口 
	I_MAIL_ENT = RuleImage(
		roi=(1135, 32, 39, 27),
		area=(1121, 18, 67, 55),
		file="./tasks/daily_routine/res/mail/mail_ent.png"
	)
	# 未读邮件 
	I_UNREAD_MAIL = RuleImage(
		roi=(166, 132, 49, 40),
		area=(112, 77, 156, 588),
		file="./tasks/daily_routine/res/mail/unread_mail.png"
	)
	# 邮件标题 
	I_MAIL_HEADER = RuleImage(
		roi=(582, 49, 113, 36),
		area=(564, 31, 149, 72),
		file="./tasks/daily_routine/res/mail/mail_header.png"
	)
	# 全部领取邮件 
	I_GET_ALL_MAIL = RuleImage(
		roi=(89, 617, 64, 56),
		area=(61, 589, 120, 112),
		file="./tasks/daily_routine/res/mail/get_all_mail.png"
	)
	# 全部领取确定 
	I_MAIL_CONFIRM = RuleImage(
		roi=(685, 545, 172, 57),
		area=(657, 517, 228, 113),
		file="./tasks/components/widgets/res/buttons/b_confirm_wide.png"
	)
	# 退出邮件窗口 
	I_MAIL_EXIT = RuleImage(
		roi=(1161, 97, 32, 34),
		area=(1145, 81, 64, 66),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)


