from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class GeneralAssets: 

	# Image Rule Assets
	# 普通召唤 
	I_REG_SUMMON = RuleImage(
		name="reg_summon",
		roi=(448, 605, 42, 58),
		area=(427, 584, 84, 100),
		file="./tasks/general/res/reg_summon.png"
	)
	# 再次召唤 
	I_SUMMON_AGAIN = RuleImage(
		name="summon_again",
		roi=(691, 621, 168, 53),
		area=(665, 595, 220, 105),
		file="./tasks/general/res/summon_again.png"
	)

	# Ocr Rule Assets
	# 普通召唤票数量 
	O_REG_SUMMON_TICKET = RuleOcr(
		roi=(565, 15, 80, 29),
		area=(565, 15, 80, 29),
		keyword="",
		name="reg_summon_ticket"
	)


