from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RealmRaidAssets: 


	# Click Rule Assets
	# 个人突破 
	C_INDIVIDUAL_RAID = RuleClick(roi=(1210, 250, 40, 75), area=(1210, 250, 40, 75), name="individual_raid")
	# 寮突破 
	C_GUILD_RAID = RuleClick(roi=(1210, 365, 40, 90), area=(1210, 365, 40, 90), name="guild_raid")

	# Ocr Rule Assets
	# 突破第一格等级位置 
	O_RAID_PARTITION_1_LV = RuleOcr(
		roi=(163, 177, 27, 25),
		area=(163, 177, 27, 25),
		keyword="",
		name="raid_partition_1_lv"
	)
	# 突破第三格等级位置 
	O_RAID_PARTITION_3_LV = RuleOcr(
		roi=(494, 310, 28, 25),
		area=(494, 310, 28, 25),
		keyword="",
		name="raid_partition_3_lv"
	)
	# 突破第九格等级位置 
	O_RAID_PARTITION_9_LV = RuleOcr(
		roi=(825, 445, 27, 25),
		area=(825, 445, 27, 25),
		keyword="",
		name="raid_partition_9_lv"
	)
	# 突破界面突破票标记位置 
	O_RAID_TICKET = RuleOcr(
		roi=(1146, 18, 73, 27),
		area=(1146, 18, 73, 27),
		keyword="",
		name="raid_ticket"
	)
	# 突破刷新等待时间位置 
	O_RAID_WAIT_TIME = RuleOcr(
		roi=(1042, 581, 83, 37),
		area=(1042, 581, 83, 37),
		keyword="",
		name="raid_wait_time"
	)
	# 寮突破票数 
	O_GUILD_RAID_TICKET = RuleOcr(
		roi=(277, 565, 40, 20),
		area=(277, 565, 40, 20),
		keyword="",
		name="guild_raid_ticket"
	)

	# Image Rule Assets
	# 结界突破界面 
	I_REALM_RAID_HEADER = RuleImage(
		roi=(574, 76, 174, 37),
		area=(556, 58, 210, 73),
		file="./tasks/realm_raid/res/realm_raid_header.png"
	)
	# 个人突破勋章排名标记 
	I_RR_RANK_ICON = RuleImage(
		roi=(14, 555, 29, 23),
		area=(2, 543, 53, 47),
		file="./tasks/realm_raid/res/rr_rank_icon.png"
	)
	# 个人突破刷新 
	I_RAID_REFRESH = RuleImage(
		roi=(1019, 586, 61, 28),
		area=(1005, 572, 89, 56),
		file="./tasks/realm_raid/res/raid_refresh.png"
	)
	# 突破队伍锁定 
	I_RAID_TEAM_LOCK = RuleImage(
		roi=(823, 581, 25, 36),
		area=(811, 569, 49, 60),
		file="./tasks/realm_raid/res/raid_team_lock.png"
	)
	# 突破队伍未锁定 
	I_RAID_TEAM_UNLOCK = RuleImage(
		roi=(823, 581, 23, 34),
		area=(811, 569, 47, 58),
		file="./tasks/realm_raid/res/raid_team_unlock.png"
	)
	# 突破队伍锁定（有活动的时候） 
	I_RAID_TEAM_LOCK_2 = RuleImage(
		roi=(1002, 645, 25, 36),
		area=(990, 633, 49, 60),
		file="./tasks/realm_raid/res/raid_team_lock.png"
	)
	# 突破队伍未锁定（有活动的时候） 
	I_RAID_TEAM_UNLOCK_2 = RuleImage(
		roi=(1003, 645, 23, 34),
		area=(991, 633, 47, 58),
		file="./tasks/realm_raid/res/raid_team_unlock.png"
	)
	# 进攻小窗口 
	I_RAID_ATTACK_MODAL = RuleImage(
		roi=(510, 489, 275, 91),
		area=(150, 310, 1130, 409),
		file="./tasks/realm_raid/res/raid_attack_modal.png"
	)
	# 进攻 
	I_RAID_ATTACK = RuleImage(
		roi=(687, 375, 62, 27),
		area=(150, 150, 1030, 569),
		file="./tasks/realm_raid/res/raid_attack.png"
	)
	# 破 
	I_RAID_BEAT = RuleImage(
		roi=(403, 303, 54, 54),
		area=(376, 276, 108, 108),
		file="./tasks/realm_raid/res/raid_beat.png"
	)
	# 挑战失败箭头 
	I_RAID_LOSE = RuleImage(
		roi=(398, 150, 66, 20),
		area=(388, 140, 86, 40),
		file="./tasks/realm_raid/res/raid_lose.png"
	)
	# 今天不再提示勾选 
	I_RAID_WARNING_CHECKBOX = RuleImage(
		roi=(538, 341, 36, 37),
		area=(520, 322, 72, 74),
		file="./tasks/realm_raid/res/raid_warning_checkbox.png"
	)
	# 突破刷新(等待) 
	I_RAID_REFRESH_UNABLE = RuleImage(
		roi=(975, 578, 71, 40),
		area=(940, 558, 142, 80),
		file="./tasks/realm_raid/res/raid_refresh_unable.png"
	)
	# 个人突破1 
	I_REALM_PARTITION_1 = RuleImage(
		roi=(240, 150, 223, 113),
		area=(240, 150, 223, 113),
		file=""
	)
	# 个人突破2 
	I_REALM_PARTITION_2 = RuleImage(
		roi=(574, 150, 220, 113),
		area=(574, 150, 220, 113),
		file=""
	)
	# 个人突破3 
	I_REALM_PARTITION_3 = RuleImage(
		roi=(903, 150, 223, 113),
		area=(903, 150, 223, 113),
		file=""
	)
	# 个人突破4 
	I_REALM_PARTITION_4 = RuleImage(
		roi=(240, 285, 223, 113),
		area=(240, 285, 223, 113),
		file=""
	)
	# 个人突破5 
	I_REALM_PARTITION_5 = RuleImage(
		roi=(574, 285, 220, 113),
		area=(574, 285, 220, 113),
		file=""
	)
	# 个人突破6 
	I_REALM_PARTITION_6 = RuleImage(
		roi=(903, 285, 223, 113),
		area=(903, 285, 223, 113),
		file=""
	)
	# 个人突破7 
	I_REALM_PARTITION_7 = RuleImage(
		roi=(240, 420, 223, 113),
		area=(240, 420, 223, 113),
		file=""
	)
	# 个人突破8 
	I_REALM_PARTITION_8 = RuleImage(
		roi=(574, 420, 220, 113),
		area=(574, 420, 220, 113),
		file=""
	)
	# 个人突破9 
	I_REALM_PARTITION_9 = RuleImage(
		roi=(903, 420, 223, 113),
		area=(903, 420, 223, 113),
		file=""
	)
	# 战斗失败 
	I_REALM_RAID_FAILED = RuleImage(
		roi=(409, 136, 125, 100),
		area=(359, 86, 225, 200),
		file="./tasks/components/battle/res/battle_failed.png"
	)
	# 式神录入口 
	I_RR_SHIKI_BOOK_ENT = RuleImage(
		roi=(1209, 617, 43, 37),
		area=(1191, 599, 79, 73),
		file="./tasks/realm_raid/res/rr_shiki_book_ent.png"
	)
	# 寮突破目标 
	I_RR_TARGET = RuleImage(
		roi=(713, 132, 33, 30),
		area=(450, 130, 655, 530),
		file="./tasks/realm_raid/res/rr_target.png"
	)
	# 寮突破进度 
	I_RR_GUID_PROGRESS = RuleImage(
		roi=(170, 313, 89, 24),
		area=(158, 301, 113, 48),
		file="./tasks/realm_raid/res/rr_guid_progress.png"
	)
	# 寮突破100%攻破 
	I_RR_GUILD_CONQUER = RuleImage(
		roi=(357, 384, 12, 17),
		area=(351, 378, 24, 29),
		file="./tasks/realm_raid/res/rr_guild_conquer.png"
	)
	# 寮突破失败标记 
	I_RR_GUILD_LOSE = RuleImage(
		roi=(675, 188, 66, 18),
		area=(666, 179, 84, 36),
		file="./tasks/realm_raid/res/rr_guild_lose.png"
	)
	# 寮突破1 
	I_GUILD_PARTITION_1 = RuleImage(
		roi=(513, 140, 228, 121),
		area=(513, 140, 228, 121),
		file=""
	)
	# 寮突破2 
	I_GUILD_PARTITION_2 = RuleImage(
		roi=(850, 140, 228, 121),
		area=(850, 140, 228, 121),
		file=""
	)
	# 寮突破3 
	I_GUILD_PARTITION_3 = RuleImage(
		roi=(513, 275, 228, 121),
		area=(513, 275, 228, 121),
		file=""
	)
	# 寮突破4 
	I_GUILD_PARTITION_4 = RuleImage(
		roi=(850, 275, 228, 121),
		area=(850, 275, 228, 121),
		file=""
	)
	# 寮突破5 
	I_GUILD_PARTITION_5 = RuleImage(
		roi=(513, 410, 228, 121),
		area=(513, 410, 228, 121),
		file=""
	)
	# 寮突破6 
	I_GUILD_PARTITION_6 = RuleImage(
		roi=(850, 410, 228, 121),
		area=(850, 410, 228, 121),
		file=""
	)
	# 寮突破未开启标记 
	I_GUILD_RAID_CLOSE = RuleImage(
		roi=(680, 218, 62, 68),
		area=(649, 187, 124, 130),
		file="./tasks/realm_raid/res/guild_raid_close.png"
	)


	# Swipe Rule Assets
	# 寮突破滑到最低 
	S_RAID_TO_BOTTOM = RuleSwipe(
		roi_start=(1121, 147, 37, 21),
		roi_end=(1121, 603, 37, 20),
		name="raid_to_bottom"
	)
	# 寮突破滑到最高 
	S_RAID_TO_TOP = RuleSwipe(
		roi_start=(1121, 603, 37, 20),
		roi_end=(1121, 147, 37, 21),
		name="raid_to_top"
	)
	# 往下翻 
	S_RAID_DOWN = RuleSwipe(
		roi_start=(745, 535, 10, 0),
		roi_end=(745, 230, 10, 0),
		name="raid_down"
	)
	# 往上翻 
	S_RAID_UP = RuleSwipe(
		roi_start=(745, 230, 10, 0),
		roi_end=(745, 535, 10, 0),
		name="raid_up"
	)


