from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class CleanSoulsAssets: 

	# Click Rule Assets
	# 御魂标记位置（六字式神名字） 
	C_SOUL_ENT_POS1 = RuleClick(roi=(550, 430, 40, 30), area=(550, 430, 40, 30), name="soul_ent_pos1")
	# 御魂标记位置（五字式神名字） 
	C_SOUL_ENT_POS2 = RuleClick(roi=(550, 400, 40, 30), area=(550, 400, 40, 30), name="soul_ent_pos2")
	# 御魂标记位置（普通式神名字） 
	C_SOUL_ENT_POS3 = RuleClick(roi=(550, 365, 40, 30), area=(550, 365, 40, 30), name="soul_ent_pos3")
	# 贪吃鬼进食习惯 
	C_SOUL_EAT_HABIT = RuleClick(roi=(830, 540, 140, 40), area=(830, 540, 140, 40), name="soul_eat_habit")
	# 贪吃鬼进食不再提示检查框 
	C_SOUL_EAT_COMFIRM_CHECKBOX = RuleClick(roi=(550, 350, 20, 20), area=(550, 350, 20, 20), name="soul_eat_comfirm_checkbox")
	# 整理灯笼 
	C_TIDY_UP_LANTERN = RuleClick(roi=(1160, 335, 60, 80), area=(1160, 335, 60, 80), name="tidy_up_lantern")
	# 奉纳灯笼 
	C_DONAT_LANTERN = RuleClick(roi=(1165, 200, 55, 80), area=(1165, 200, 55, 80), name="donat_lantern")
	# 弃置(方案) 
	C_DUMP_SCHEME = RuleClick(roi=(655, 180, 80, 45), area=(655, 180, 80, 45), name="dump_scheme")
	# 强化(方案) 
	C_UPGRADE_SCHEME = RuleClick(roi=(755, 180, 75, 45), area=(755, 180, 75, 45), name="upgrade_scheme")
	# 筛选 
	C_FILTERS = RuleClick(roi=(645, 110, 90, 35), area=(645, 110, 90, 35), name="filters")
	# 方案 
	C_SCHEMES = RuleClick(roi=(760, 110, 90, 35), area=(760, 110, 90, 35), name="schemes")
	# 已弃置 
	C_DUMPED_SOULS = RuleClick(roi=(45, 95, 95, 35), area=(45, 95, 95, 35), name="dumped_souls")
	# 待整理 
	C_UNTIDY_SOULS = RuleClick(roi=(165, 95, 90, 35), area=(165, 95, 90, 35), name="untidy_souls")
	# left 
	C_RANDOM_CLICK = RuleClick(roi=(110, 130, 130, 300), area=(110, 130, 130, 300), name="random_click")

	# Image Rule Assets
	# 贪吃鬼 
	I_SOUL_GREED = RuleImage(
		name="soul_greed",
		roi=(1160, 617, 56, 48),
		area=(1136, 593, 104, 96),
		file="./tasks/components/clean_souls/res/soul_greed.png"
	)
	# 贪吃鬼小屋 
	I_SOUL_GREED_CHECK = RuleImage(
		name="soul_greed_check",
		roi=(326, 263, 92, 65),
		area=(294, 231, 156, 129),
		file="./tasks/components/clean_souls/res/soul_greed_check.png"
	)
	# 立刻进食 
	I_SOUL_GREED_EAT = RuleImage(
		name="soul_greed_eat",
		roi=(933, 601, 72, 58),
		area=(904, 572, 130, 116),
		file="./tasks/components/clean_souls/res/soul_greed_eat.png"
	)
	# 确定进食 
	I_SOUL_GREED_EAT_CONFIRM = RuleImage(
		name="soul_greed_eat_confirm",
		roi=(672, 403, 172, 57),
		area=(644, 375, 228, 113),
		file="./tasks/components/widgets/res/buttons/b_confirm_wide.png"
	)
	# 关闭贪吃鬼小屋 
	I_SOUL_GREED_CLOSE = RuleImage(
		name="soul_greed_close",
		roi=(936, 216, 29, 30),
		area=(922, 202, 57, 58),
		file="./tasks/components/clean_souls/res/soul_greed_close.png"
	)
	# 批量强化 
	I_MASS_UPGRADE_ICON = RuleImage(
		name="mass_upgrade_icon",
		roi=(45, 637, 54, 51),
		area=(19, 611, 106, 103),
		file="./tasks/components/clean_souls/res/mass_upgrade_icon.png"
	)
	# 招财猫 
	I_MANEKI_NEKO = RuleImage(
		name="maneki_neko",
		roi=(806, 233, 45, 33),
		area=(790, 217, 77, 65),
		file="./tasks/components/clean_souls/res/maneki_neko.png"
	)
	# 弃置图标 
	I_DUMP_ICON = RuleImage(
		name="dump_icon",
		roi=(252, 653, 27, 24),
		area=(240, 641, 51, 48),
		file="./tasks/components/clean_souls/res/dump_icon.png"
	)
	# 锁定图标(灰) 
	I_LOCK_ICON = RuleImage(
		name="lock_icon",
		roi=(256, 652, 20, 22),
		area=(246, 642, 40, 42),
		file="./tasks/components/clean_souls/res/lock_icon.png"
	)
	# 全选方案 
	I_SELECT_ALL_SCHEMES = RuleImage(
		name="select_all_schemes",
		roi=(959, 207, 31, 24),
		area=(947, 195, 55, 48),
		file="./tasks/components/clean_souls/res/select_all.png"
	)
	# 全选御魂 
	I_SELECT_ALL_SOULS = RuleImage(
		name="select_all_souls",
		roi=(487, 102, 31, 24),
		area=(475, 90, 55, 48),
		file="./tasks/components/clean_souls/res/select_all.png"
	)
	# 方案码导入图标 
	I_SCHEME_IMPORT_ICON = RuleImage(
		name="scheme_import_icon",
		roi=(619, 652, 32, 32),
		area=(603, 636, 64, 64),
		file="./tasks/components/clean_souls/res/scheme_import_icon.png"
	)
	# 无符合条件御魂时的灯笼 
	I_EMPTY_LANTERN = RuleImage(
		name="empty_lantern",
		roi=(244, 287, 114, 152),
		area=(187, 230, 228, 266),
		file="./tasks/components/clean_souls/res/empty_lantern.png"
	)
	# 恢复 
	I_RECOVER = RuleImage(
		name="recover",
		roi=(274, 651, 60, 28),
		area=(260, 637, 88, 56),
		file="./tasks/components/clean_souls/res/recover.png"
	)
	# 3号方案 
	I_SCHEME_3 = RuleImage(
		name="scheme_3",
		roi=(661, 415, 11, 17),
		area=(655, 409, 23, 29),
		file="./tasks/components/clean_souls/res/scheme_3.png"
	)


