from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class YulingAssets: 

	# Image Rule Assets
	# 御灵标记 
	I_YL_CHECK = RuleImage(
		roi=(113, 24, 66, 38),
		area=(94, 5, 104, 76),
		file="./tasks/yuling/res/yl_check.png"
	)
	# 御灵挑战 
	I_YL_FIGHT = RuleImage(
		roi=(1109, 602, 74, 72),
		area=(1073, 566, 146, 144),
		file="./tasks/yuling/res/yl_fight.png"
	)
	# 御灵三层 
	I_YL_LV_3 = RuleImage(
		roi=(288, 512, 65, 28),
		area=(274, 498, 93, 56),
		file="./tasks/yuling/res/yl_lv_3.png"
	)


