from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RoyalBattleAssets: 

	# Image Rule Assets
	# 斗技入口 
	I_RB_ENT = RuleImage(
		roi=(125, 303, 48, 44),
		area=(20, 281, 800, 88),
		file="./tasks/royal_battle/res/rb_ent.png"
	)
	# 斗技比赛 
	I_RB_CONTEST_CHECK = RuleImage(
		roi=(95, 5, 144, 45),
		area=(73, 0, 188, 89),
		file="./tasks/royal_battle/res/rb_contest_check.png"
	)
	# 斗技比赛对战 
	I_RB_CONTEST_FIGHT = RuleImage(
		roi=(1161, 589, 88, 93),
		area=(1117, 545, 176, 181),
		file="./tasks/royal_battle/res/rb_contest_fight.png"
	)
	# 战斗黄色 
	I_RB_FIGHT = RuleImage(
		roi=(1146, 575, 101, 87),
		area=(1102, 531, 189, 175),
		file="./tasks/royal_battle/res/rb_fight.png"
	)
	# 战斗蓝色 
	I_RB_FIGHT_BLUE = RuleImage(
		roi=(1156, 571, 75, 72),
		area=(1120, 535, 147, 144),
		file="./tasks/royal_battle/res/rb_fight_blue.png"
	)
	#  
	I_RB_CHECK = RuleImage(
		roi=(97, 5, 142, 45),
		area=(75, 0, 186, 89),
		file="./tasks/royal_battle/res/rb_check.png"
	)
	# 日常界面 
	I_RB_DAILY = RuleImage(
		roi=(531, 56, 214, 56),
		area=(503, 28, 270, 112),
		file="./tasks/royal_battle/res/rb_daily.png"
	)
	# 日常界面斗技图标 
	I_RB_LOGO = RuleImage(
		roi=(700, 163, 59, 56),
		area=(210, 120, 870, 500),
		file="./tasks/royal_battle/res/rb_logo.png"
	)
	# 斗技标题图标 
	I_RB_HEADER = RuleImage(
		roi=(470, 167, 107, 102),
		area=(419, 116, 209, 204),
		file="./tasks/royal_battle/res/rb_header.png"
	)
	# 前往 
	I_RB_GOTO = RuleImage(
		roi=(571, 484, 131, 65),
		area=(539, 452, 195, 129),
		file="./tasks/royal_battle/res/rb_goto.png"
	)
	# 斗技准备 
	I_RB_READY = RuleImage(
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/battle/res/battle_ready.png"
	)
	# 斗技胜利 
	I_RB_WIN = RuleImage(
		roi=(411, 54, 172, 129),
		area=(347, 0, 300, 257),
		file="./tasks/battle/res/battle_win.png"
	)
	# 段位上升 
	I_RB_UPGRADE = RuleImage(
		roi=(323, 291, 136, 65),
		area=(291, 259, 200, 129),
		file="./tasks/royal_battle/res/rb_upgrade.png"
	)
	# 自动上阵 
	I_RB_AUTO_TEAM = RuleImage(
		roi=(39, 132, 45, 54),
		area=(17, 110, 89, 98),
		file="./tasks/royal_battle/res/rb_auto_team.png"
	)
	# 战斗失败 
	I_RB_BATTLE_FAILED = RuleImage(
		roi=(409, 68, 125, 100),
		area=(359, 18, 225, 200),
		file="./tasks/battle/res/battle_failed.png"
	)
	# 上阵战图标 
	I_RB_TEAM_PREP_CHECK = RuleImage(
		roi=(611, 40, 58, 55),
		area=(583, 12, 114, 111),
		file="./tasks/royal_battle/res/rb_team_prep_check.png"
	)
	# 名士徽章 
	I_RB_NOTABLE_BADGE = RuleImage(
		roi=(668, 535, 23, 20),
		area=(658, 525, 43, 40),
		file="./tasks/royal_battle/res/rb_notable_badge.png"
	)
	# 普通花朵徽章 
	I_RB_FLOWER_BADGE = RuleImage(
		roi=(665, 507, 38, 36),
		area=(647, 489, 74, 72),
		file="./tasks/royal_battle/res/rb_flower_badge.png"
	)

	# Ocr Rule Assets
	# 斗技分数 
	O_RB_SCORE = RuleOcr(
		roi=(704, 512, 50, 23),
		area=(692, 500, 74, 47),
		keyword="",
		name="rb_score"
	)


	# Swipe Rule Assets
	# 往左滑动,往右走 
	S_RB_TO_RIGHT = RuleSwipe(
		roi_start=(700, 200, 200, 300),
		roi_end=(150, 200, 350, 300),
		name="rb_to_right"
	)
	# 往右滑动,往左走 
	S_RB_TO_LEFT = RuleSwipe(
		roi_start=(200, 200, 400, 300),
		roi_end=(800, 200, 100, 300),
		name="rb_to_left"
	)


