from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class RoyalBattleAssets: 


	# Click Rule Assets
	# 晴明 
	C_SEIMEI = RuleClick(roi=(170, 180, 180, 320), area=(170, 180, 180, 320), name="Seimei")
	# 神乐 
	C_KAGURA = RuleClick(roi=(420, 180, 180, 320), area=(420, 180, 180, 320), name="Kagura")
	# 源博雅 
	C_HIROMASA = RuleClick(roi=(670, 180, 180, 320), area=(670, 180, 180, 320), name="Hiromasa")
	# 八百比丘尼 
	C_YAOBIKUNI = RuleClick(roi=(930, 180, 180, 320), area=(930, 180, 180, 320), name="Yaobikuni")
	# 更换阴阳师类型 
	C_SWITCH_TYPE = RuleClick(roi=(30, 610, 25, 20), area=(30, 610, 25, 20), name="switch_type")

	# Image Rule Assets
	# 斗技入口 
	I_RB_ENT = RuleImage(
		roi=(125, 303, 48, 44),
		area=(20, 281, 800, 88),
		file="./tasks/royal_battle/res/rb_ent.png"
	)
	# 町中武馆斗技 
	I_DOJO_TO_ROYAL_BATTLE = RuleImage(
		roi=(720, 254, 24, 53),
		area=(708, 242, 48, 77),
		file="./tasks/general/res/check/c_dojo.png"
	)
	# 斗技比赛 
	I_RB_CONTEST_CHECK = RuleImage(
		roi=(95, 5, 144, 45),
		area=(73, 0, 188, 89),
		file="./tasks/royal_battle/res/rb_contest_check.png"
	)
	# 斗技比赛对战 
	I_RB_CONTEST_FIGHT = RuleImage(
		roi=(1161, 589, 88, 93),
		area=(1117, 545, 176, 181),
		file="./tasks/royal_battle/res/rb_contest_fight.png"
	)
	# 战斗黄色 
	I_RB_FIGHT = RuleImage(
		roi=(1146, 575, 101, 87),
		area=(1102, 531, 189, 175),
		file="./tasks/royal_battle/res/rb_fight.png"
	)
	# 战斗蓝色 
	I_RB_FIGHT_BLUE = RuleImage(
		roi=(1156, 571, 75, 72),
		area=(1120, 535, 147, 144),
		file="./tasks/royal_battle/res/rb_fight_blue.png"
	)
	#  
	I_RB_CHECK = RuleImage(
		roi=(97, 5, 142, 45),
		area=(75, 0, 186, 89),
		file="./tasks/royal_battle/res/rb_check.png"
	)
	# 日常界面 
	I_RB_DAILY = RuleImage(
		roi=(531, 56, 214, 56),
		area=(503, 28, 270, 112),
		file="./tasks/royal_battle/res/rb_daily.png"
	)
	# 日常界面斗技图标 
	I_RB_LOGO = RuleImage(
		roi=(700, 163, 59, 56),
		area=(210, 120, 870, 500),
		file="./tasks/royal_battle/res/rb_logo.png"
	)
	# 斗技标题图标 
	I_RB_HEADER = RuleImage(
		roi=(470, 167, 107, 102),
		area=(419, 116, 209, 204),
		file="./tasks/royal_battle/res/rb_header.png"
	)
	# 前往 
	I_RB_GOTO = RuleImage(
		roi=(571, 484, 131, 65),
		area=(539, 452, 195, 129),
		file="./tasks/royal_battle/res/rb_goto.png"
	)
	# 斗技准备 
	I_RB_READY = RuleImage(
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/battle/res/battle_ready.png"
	)
	# 斗技胜利 
	I_RB_WIN = RuleImage(
		roi=(411, 54, 172, 129),
		area=(347, 0, 300, 257),
		file="./tasks/battle/res/battle_win.png"
	)
	# 段位上升 
	I_RB_UPGRADE = RuleImage(
		roi=(323, 291, 136, 65),
		area=(291, 259, 200, 129),
		file="./tasks/royal_battle/res/rb_upgrade.png"
	)
	# 自动上阵 
	I_RB_AUTO_TEAM = RuleImage(
		roi=(39, 132, 45, 54),
		area=(17, 110, 89, 98),
		file="./tasks/royal_battle/res/rb_auto_team.png"
	)
	# 战斗失败 
	I_RB_BATTLE_FAILED = RuleImage(
		roi=(409, 68, 125, 100),
		area=(359, 18, 225, 200),
		file="./tasks/battle/res/battle_failed.png"
	)
	# 上阵战图标 
	I_RB_TEAM_PREP_CHECK = RuleImage(
		roi=(611, 40, 58, 55),
		area=(583, 12, 114, 111),
		file="./tasks/royal_battle/res/rb_team_prep_check.png"
	)
	# 名士徽章 
	I_RB_NOTABLE_BADGE = RuleImage(
		roi=(668, 535, 23, 20),
		area=(658, 525, 43, 40),
		file="./tasks/royal_battle/res/rb_notable_badge.png"
	)
	# 普通花朵徽章 
	I_RB_FLOWER_BADGE = RuleImage(
		roi=(665, 507, 38, 36),
		area=(647, 489, 74, 72),
		file="./tasks/royal_battle/res/rb_flower_badge.png"
	)
	# 晋升名士 
	I_RB_NOTABLE_NOTIFICATION = RuleImage(
		roi=(504, 399, 286, 70),
		area=(469, 364, 356, 140),
		file="./tasks/royal_battle/res/rb_notable_notification.png"
	)
	# 阴阳术页面 
	I_C_ONMYODO = RuleImage(
		roi=(102, 9, 96, 34),
		area=(85, 0, 130, 68),
		file="./tasks/royal_battle/res/c_onmyodo.png"
	)
	# 交换阴阳师 
	I_CHANGE_ONMYOJI = RuleImage(
		roi=(38, 387, 41, 31),
		area=(22, 371, 73, 63),
		file="./tasks/royal_battle/res/change_onmyoji.png"
	)
	# 阴阳师交换页面 
	I_C_CHANGE_PAGE = RuleImage(
		roi=(92, 13, 177, 38),
		area=(73, 0, 215, 76),
		file="./tasks/royal_battle/res/c_change_page.png"
	)
	# 阴阳师选中 
	I_ONMYOJI_SELECTED = RuleImage(
		roi=(57, 631, 105, 39),
		area=(37, 611, 145, 79),
		file="./tasks/royal_battle/res/onmyoji_selected.png"
	)
	# 英杰选中 
	I_HERO_SELECTED = RuleImage(
		roi=(72, 630, 71, 38),
		area=(53, 611, 109, 76),
		file="./tasks/royal_battle/res/hero_selected.png"
	)
	# 退出阴阳术 
	I_EXIT_ONMYODO = RuleImage(
		roi=(22, 7, 42, 41),
		area=(2, 0, 82, 81),
		file="./tasks/general/res/buttons/b_yellow_left_angle.png"
	)
	# 阴阳术入口 
	I_MAIN_ONMYODO_ENT = RuleImage(
		roi=(998, 618, 38, 35),
		area=(980, 600, 74, 71),
		file="./tasks/royal_battle/res/main_onmyodo_ent.png"
	)
	#  
	I_EXIT_CHANGE_PAGE = RuleImage(
		roi=(11, 13, 53, 44),
		area=(0, 0, 97, 88),
		file="./tasks/general/res/buttons/b_blue_left_angle.png"
	)

	# Ocr Rule Assets
	# 斗技分数 
	O_RB_SCORE = RuleOcr(
		roi=(704, 512, 50, 23),
		area=(692, 500, 74, 47),
		keyword="",
		name="rb_score"
	)


	# Swipe Rule Assets
	# 往左滑动,往右走 
	S_RB_TO_RIGHT = RuleSwipe(
		roi_start=(700, 200, 200, 300),
		roi_end=(150, 200, 350, 300),
		name="rb_to_right"
	)
	# 往右滑动,往左走 
	S_RB_TO_LEFT = RuleSwipe(
		roi_start=(200, 200, 400, 300),
		roi_end=(800, 200, 100, 300),
		name="rb_to_left"
	)


