from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class NetherworldAssets: 

	# Image Rule Assets
	# 阴界之门图标（右下角） 
	I_NW_ENT = RuleImage(
		name="nw_ent",
		roi=(1074, 611, 76, 75),
		area=(1036, 573, 152, 151),
		file="./tasks/netherworld/res/nw_ent.png"
	)
	# 退出阴界之门 
	I_NW_PAGE_EXIT = RuleImage(
		name="nw_page_exit",
		roi=(55, 37, 53, 44),
		area=(33, 15, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 挑战方形按钮 
	I_NW_CHALLENGE = RuleImage(
		name="nw_challenge",
		roi=(362, 607, 60, 28),
		area=(348, 593, 88, 56),
		file="./tasks/netherworld/res/nw_challenge.png"
	)
	# 式神录入口 
	I_NW_SHIKI_BOOK_ENT = RuleImage(
		name="nw_shiki_book_ent",
		roi=(146, 601, 43, 39),
		area=(126, 581, 83, 79),
		file="./tasks/netherworld/res/nw_shiki_book_ent.png"
	)
	# 阴界之门页眉 
	I_NW_HEADER = RuleImage(
		name="nw_header",
		roi=(566, 48, 122, 31),
		area=(550, 32, 154, 63),
		file="./tasks/netherworld/res/nw_header.png"
	)
	# 挑战（组队页面） 
	I_NW_BATTLE_CHALLENGE = RuleImage(
		name="nw_battle_challenge",
		roi=(1185, 618, 63, 50),
		area=(1160, 593, 113, 100),
		file="./tasks/netherworld/res/nw_battle_challenge.png"
	)
	# 阴界之门寮入口 
	I_NW_GUILD_ENT = RuleImage(
		name="nw_guild_ent",
		roi=(36, 167, 77, 20),
		area=(26, 157, 97, 40),
		file="./tasks/netherworld/res/nw_guild_ent.png"
	)
	# 确定从36轮开始 
	I_NW_BATTLE_CONFIRM = RuleImage(
		name="nw_battle_confirm",
		roi=(672, 403, 172, 57),
		area=(644, 375, 228, 113),
		file="./tasks/components/widgets/res/buttons/b_confirm_wide.png"
	)


