from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class DokanAssets: 

	# Click Rule Assets
	# 胜利战报空白点击 
	C_WIN_BLANK = RuleClick(roi=(1160, 140, 100, 400), area=(1160, 140, 100, 400), name="win_blank")
	# 左边第一个式神 
	C_SHIKI_LEFT_1 = RuleClick(roi=(200, 440, 60, 80), area=(200, 440, 60, 80), name="shiki_left_1")

	# Image Rule Assets
	# 道馆寮入口 
	I_DK_GUILD_ENT = RuleImage(
		name="dk_guild_ent",
		roi=(34, 166, 40, 21),
		area=(10, 150, 190, 400),
		file="./tasks/dokan/res/dk_guild_ent.png"
	)
	# 道馆地图页面 
	I_DK_MAP_CHECK = RuleImage(
		name="dk_map_check",
		roi=(98, 36, 128, 32),
		area=(82, 20, 160, 64),
		file="./tasks/dokan/res/dk_map_check.png"
	)
	# 目标道馆 
	I_TARGET_DOKAN = RuleImage(
		name="target_dokan",
		roi=(297, 202, 114, 15),
		area=(40, 100, 1100, 500),
		file="./tasks/dokan/res/target_dokan.png"
	)
	# 道馆页面 
	I_DK_PAGE_HEADER = RuleImage(
		name="dk_page_header",
		roi=(573, 19, 136, 34),
		area=(556, 2, 170, 68),
		file="./tasks/dokan/res/dk_page_header.png"
	)
	# 挑战 
	I_DK_CHALLENGE = RuleImage(
		name="dk_challenge",
		roi=(1133, 573, 82, 42),
		area=(1112, 552, 124, 84),
		file="./tasks/dokan/res/dk_challenge.png"
	)
	# 击败馆主通知 
	I_DK_CONQUER_SWORD = RuleImage(
		name="dk_conquer_sword",
		roi=(556, 394, 167, 83),
		area=(514, 352, 251, 167),
		file="./tasks/dokan/res/dk_conquer_sword.png"
	)
	# 胜利战报 
	I_DK_WIN_SMALL = RuleImage(
		name="dk_win_small",
		roi=(423, 39, 168, 82),
		area=(382, 0, 250, 164),
		file="./tasks/dokan/res/dk_win_small.png"
	)
	# 胜利 
	I_DK_WIN_LARGE = RuleImage(
		name="dk_win_large",
		roi=(414, 45, 195, 105),
		area=(362, 0, 299, 209),
		file="./tasks/dokan/res/dk_win_large.png"
	)
	# 退出道馆 
	I_DK_DOKAN_EXIT = RuleImage(
		name="dk_dokan_exit",
		roi=(21, 21, 30, 30),
		area=(6, 6, 60, 60),
		file="./tasks/components/widgets/res/buttons/b_return_u.png"
	)
	# 退出确认 
	I_DK_EXIT_CONFIRM = RuleImage(
		name="dk_exit_confirm",
		roi=(679, 396, 124, 52),
		area=(653, 370, 176, 104),
		file="./tasks/components/widgets/res/buttons/b_confirm_narrow.png"
	)
	# 退出道馆地图页面 
	I_DK_MAP_EXIT = RuleImage(
		name="dk_map_exit",
		roi=(19, 28, 53, 44),
		area=(-3, 6, 97, 88),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 道馆式神录入口 
	I_DK_SHIKI_BOOK_ENT = RuleImage(
		name="dk_shiki_book_ent",
		roi=(985, 608, 80, 55),
		area=(957, 580, 136, 111),
		file="./tasks/dokan/res/dk_shiki_book_ent.png"
	)
	# 馆主挑战通知 
	I_DOKAN_LAST_FIGHT_NOTICE = RuleImage(
		name="dokan_last_fight_notice",
		roi=(531, 183, 221, 18),
		area=(522, 174, 239, 36),
		file="./tasks/dokan/res/dokan_last_fight_notice.png"
	)


