from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class BuffAssets: 

	# Image Rule Assets
	# 庭院左上角的加成灯笼 
	I_BUFF_OPEN = RuleImage(
		roi=(363, 32, 32, 46),
		area=(347, 16, 64, 78),
		file="./tasks/buff/res/buff_open.png"
	)
	# 探索界面加成灯笼 
	I_EXP_BUFF_OPEN = RuleImage(
		roi=(427, 23, 29, 44),
		area=(413, 9, 57, 72),
		file="./tasks/buff/res/exp_buff_open.png"
	)
	# 鬼兵演武界面加成灯笼 
	I_MINAMOTO_BUFF_OPEN = RuleImage(
		roi=(809, 35, 29, 42),
		area=(795, 21, 57, 70),
		file="./tasks/buff/res/minamoto_buff_open.png"
	)
	# 加成窗口下面的云，用来检测和关闭 
	I_BUFF_CLOUD = RuleImage(
		roi=(386, 515, 122, 24),
		area=(374, 503, 146, 48),
		file="./tasks/buff/res/buff_cloud.png"
	)
	# 觉醒加成(开) 
	I_BUFF_AWAKE_ACTIVATE = RuleImage(
		roi=(770, 140, 47, 46),
		area=(770, 140, 80, 30),
		file="./tasks/buff/res/buff_open_yellow.png"
	)
	# 觉醒加成(关) 
	I_BUFF_AWAKE_DEACTIVATE = RuleImage(
		roi=(770, 140, 47, 46),
		area=(770, 140, 80, 30),
		file="./tasks/buff/res/buff_close_red.png"
	)
	# 御魂加成(开) 
	I_BUFF_SOUL_ACTIVATE = RuleImage(
		roi=(770, 200, 45, 46),
		area=(770, 200, 80, 30),
		file="./tasks/buff/res/buff_open_yellow.png"
	)
	# 御魂加成(关) 
	I_BUFF_SOUL_DEACTIVATE = RuleImage(
		roi=(770, 200, 45, 46),
		area=(770, 200, 80, 30),
		file="./tasks/buff/res/buff_close_red.png"
	)
	# 金币50%加成(开) 
	I_BUFF_GOLD_50_ACTIVATE = RuleImage(
		roi=(770, 275, 52, 36),
		area=(770, 275, 80, 30),
		file="./tasks/buff/res/buff_open_yellow.png"
	)
	# 金币50%加成(关) 
	I_BUFF_GOLD_50_DEACTIVATE = RuleImage(
		roi=(770, 275, 52, 36),
		area=(770, 275, 80, 30),
		file="./tasks/buff/res/buff_close_red.png"
	)
	# 金币100%加成(开) 
	I_BUFF_GOLD_100_ACTIVATE = RuleImage(
		roi=(770, 340, 43, 39),
		area=(770, 340, 80, 30),
		file="./tasks/buff/res/buff_open_yellow.png"
	)
	# 金币100%加成(关) 
	I_BUFF_GOLD_100_DEACTIVATE = RuleImage(
		roi=(770, 340, 43, 39),
		area=(770, 340, 80, 30),
		file="./tasks/buff/res/buff_close_red.png"
	)
	# 经验50%加成(开) 
	I_BUFF_EXP_50_ACTIVATE = RuleImage(
		roi=(770, 410, 44, 43),
		area=(770, 410, 80, 30),
		file="./tasks/buff/res/buff_open_yellow.png"
	)
	# 经验50%加成(关) 
	I_BUFF_EXP_50_DEACTIVATE = RuleImage(
		roi=(770, 410, 44, 43),
		area=(770, 410, 80, 30),
		file="./tasks/buff/res/buff_close_red.png"
	)
	# 经验100%加成(开) 
	I_BUFF_EXP_100_ACTIVATE = RuleImage(
		roi=(770, 470, 30, 40),
		area=(770, 470, 80, 30),
		file="./tasks/buff/res/buff_open_yellow.png"
	)
	# 经验100%加成(关) 
	I_BUFF_EXP_100_DEACTIVATE = RuleImage(
		roi=(770, 470, 30, 40),
		area=(770, 470, 80, 30),
		file="./tasks/buff/res/buff_close_red.png"
	)

	# Ocr Rule Assets
	# Ocr-description 
	O_GOLD_50 = RuleOcr(
		roi=(428,120,338,389),
		area=(0,0,100,100),
		keyword="战斗胜利获得的金币增加50%",
		name="gold_50"
	)
	# Ocr-description 
	O_GOLD_100 = RuleOcr(
		roi=(425,118,342,397),
		area=(0,0,100,100),
		keyword="战斗胜利获得的金币增加100%",
		name="gold_100"
	)
	# Ocr-description 
	O_EXP_50 = RuleOcr(
		roi=(426,119,335,394),
		area=(0,0,100,100),
		keyword="战斗胜利获得的经验增加50%",
		name="exp_50"
	)
	# Ocr-description 
	O_EXP_100 = RuleOcr(
		roi=(421,127,342,388),
		area=(0,0,100,100),
		keyword="战斗胜利获得的经验增加100%",
		name="exp_100"
	)


	# Swipe Rule Assets
	# description 
	S_BUFF_UP = RuleSwipe(
		roi_start=(397,124,456,35),
		roi_end=(447,457,386,37),
		name="buff_up"
	)


