from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class WidgetsAssets: 

	# Image Rule Assets
	# 红色X 
	I_B_RED_X = RuleImage(
		roi=(1194, 27, 32, 34),
		area=(500, 10, 700, 700),
		file="./tasks/components/widgets/res/buttons/b_red_x.png"
	)
	# 蓝色<退出 
	I_B_BLUE_LEFT_ANGLE = RuleImage(
		roi=(24, 36, 53, 44),
		area=(0, 0, 300, 200),
		file="./tasks/components/widgets/res/buttons/b_blue_left_angle.png"
	)
	# 黄色<退出 
	I_B_YELLOW_LEFT_ANGLE = RuleImage(
		roi=(34, 9, 42, 41),
		area=(0, 0, 300, 300),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)
	# 获得奖励栏标 
	I_GAIN_REWARD = RuleImage(
		roi=(476, 233, 329, 42),
		area=(312, 212, 658, 84),
		file="./tasks/components/widgets/res/signs/gain_reward.png"
	)
	# 战斗/突破/宝箱奖励领取图标 
	I_REWARD = RuleImage(
		roi=(565, 444, 137, 165),
		area=(497, 376, 273, 301),
		file="./tasks/components/widgets/res/signs/reward.png"
	)


