from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class ShikigamiActivityAssets: 

	# Click Rule Assets
	# left 
	C_SA_REWARD_LEFT = RuleClick(roi=(40, 80, 220, 660), area=(40, 80, 220, 660), name="sa_reward_left")
	# bottom 
	C_SA_REWARD_BOTTOM = RuleClick(roi=(30, 600, 1200, 100), area=(30, 600, 1200, 100), name="sa_reward_bottom")
	# right 
	C_SA_REWARD_RIGHT = RuleClick(roi=(1010, 80, 250, 620), area=(1010, 80, 250, 620), name="sa_reward_right")
	# 战斗简单模式 
	C_SA_FIGHT_EASY = RuleClick(roi=(1182, 259, 50, 40), area=(1182, 259, 50, 40), name="sa_fight_easy")
	# 战斗困难模式 
	C_SA_FIGHT_HARD = RuleClick(roi=(1172, 365, 59, 45), area=(1172, 365, 59, 45), name="sa_fight_hard")

	# Image Rule Assets
	# 庭院活动入口 
	I_SA_MAIN_ENT = RuleImage(
		name="sa_main_ent",
		roi=(454, 306, 28, 68),
		area=(400, 290, 140, 100),
		file="./tasks/shikigami_activity/res/sa_main_ent.png"
	)
	# 活动页面确认 
	I_SA_MAIN_CHECK = RuleImage(
		name="sa_main_check",
		roi=(91, 21, 126, 33),
		area=(75, 5, 158, 65),
		file="./tasks/shikigami_activity/res/sa_main_check.png"
	)
	# 爬塔入口 
	I_SA_FIGHT_PAGE_ENT = RuleImage(
		name="sa_fight_page_ent",
		roi=(481, 211, 25, 114),
		area=(469, 199, 49, 138),
		file="./tasks/shikigami_activity/res/sa_fight_page_ent.png"
	)
	# 爬塔页面确认 
	I_SA_FIGHT_PAGE_CHECK = RuleImage(
		name="sa_fight_page_check",
		roi=(93, 21, 124, 32),
		area=(77, 5, 156, 64),
		file="./tasks/shikigami_activity/res/sa_fight_page_check.png"
	)
	# 爬塔战斗目标（个别情况） 
	I_SA_FIGHT_TARGET = RuleImage(
		name="sa_fight_target",
		roi=(487, 386, 54, 47),
		area=(40, 70, 1200, 640),
		file="./tasks/shikigami_activity/res/sa_fight_target.png"
	)
	# 爬塔战斗目标挑战页面 
	I_SA_FIGHT_TARGET_PAGE_CHECK = RuleImage(
		name="sa_fight_target_page_check",
		roi=(92, 20, 123, 34),
		area=(75, 3, 157, 68),
		file="./tasks/shikigami_activity/res/sa_fight_target_page_check.png"
	)
	# 战斗 
	I_SA_FIGHT = RuleImage(
		name="sa_fight",
		roi=(1132, 599, 97, 54),
		area=(1105, 572, 151, 108),
		file="./tasks/shikigami_activity/res/sa_fight.png"
	)
	# 式神录入口 
	I_SA_SHIKI_BOOK_ENT = RuleImage(
		name="sa_shiki_book_ent",
		roi=(1033, 559, 36, 38),
		area=(1015, 541, 72, 74),
		file="./tasks/shikigami_activity/res/sa_shiki_book_ent.png"
	)
	# 爬塔商店弹窗 
	I_SA_SHOP = RuleImage(
		name="sa_shop",
		roi=(362, 97, 90, 41),
		area=(342, 77, 130, 81),
		file="./tasks/shikigami_activity/res/sa_shop.png"
	)
	# 使用体力 
	I_SA_AP = RuleImage(
		name="sa_ap",
		roi=(1091, 549, 23, 26),
		area=(1079, 537, 47, 50),
		file="./tasks/shikigami_activity/res/sa_ap.png"
	)
	# 使用爬塔门票 
	I_SA_TICKET = RuleImage(
		name="sa_ticket",
		roi=(1148, 553, 11, 9),
		area=(1144, 549, 19, 17),
		file="./tasks/shikigami_activity/res/sa_ticket.png"
	)
	# 体力门票转换 
	I_SA_SWITCH = RuleImage(
		name="sa_switch",
		roi=(1244, 552, 23, 22),
		area=(1200, 541, 75, 44),
		file="./tasks/shikigami_activity/res/sa_switch.png"
	)
	# 队伍不锁定 
	I_SA_TEAM_UNLOCK = RuleImage(
		name="sa_team_unlock",
		roi=(817, 648, 17, 24),
		area=(810, 640, 105, 40),
		file="./tasks/shikigami_activity/res/sa_team_unlock.png"
	)
	# 队伍锁定 
	I_SA_TEAM_LOCK = RuleImage(
		name="sa_team_lock",
		roi=(816, 648, 19, 28),
		area=(805, 640, 110, 40),
		file="./tasks/shikigami_activity/res/sa_team_lock.png"
	)
	# 退出 
	I_SA_EXIT = RuleImage(
		name="sa_exit",
		roi=(20, 16, 42, 41),
		area=(0, 0, 82, 81),
		file="./tasks/components/widgets/res/buttons/b_yellow_left_angle.png"
	)
	# 没票了 
	I_SA_NO_TICKETS = RuleImage(
		name="sa_no_tickets",
		roi=(675, 27, 135, 26),
		area=(662, 14, 161, 52),
		file="./tasks/shikigami_activity/res/sa_no_tickets.png"
	)
	# 胜利 
	I_SA_BATTLE_WIN = RuleImage(
		name="sa_battle_win",
		roi=(411, 122, 172, 129),
		area=(347, 58, 300, 257),
		file="./tasks/components/battle/res/battle_win.png"
	)
	# 召唤鬼王 
	I_SA_SUMMON = RuleImage(
		name="sa_summon",
		roi=(1136, 580, 90, 89),
		area=(1092, 536, 178, 177),
		file="./tasks/shikigami_activity/res/sa_summon.png"
	)
	# 鬼王挑战 
	I_SA_SUMMON_FIGHT = RuleImage(
		name="sa_summon_fight",
		roi=(1128, 595, 107, 62),
		area=(1097, 564, 169, 124),
		file="./tasks/shikigami_activity/res/sa_summon_fight.png"
	)
	# 鬼王挑战准备 
	I_SA_BATTLE_READY = RuleImage(
		name="sa_battle_ready",
		roi=(1135, 565, 87, 46),
		area=(1112, 542, 133, 92),
		file="./tasks/components/battle/res/battle_ready.png"
	)
	# 战斗确认 
	I_SA_BATTLE_CHECK = RuleImage(
		name="sa_battle_check",
		roi=(659, 687, 25, 33),
		area=(647, 675, 49, 57),
		file="./tasks/shikigami_activity/res/sa_battle_check.png"
	)
	# 活动币（战斗奖励） 
	I_SA_COIN = RuleImage(
		name="sa_coin",
		roi=(427, 280, 52, 38),
		area=(408, 261, 90, 76),
		file="./tasks/shikigami_activity/res/sa_coin.png"
	)

	# Ocr Rule Assets
	# 爬塔门票数量 
	O_TICKET_COUNT = RuleOcr(
		roi=(540, 20, 67, 22),
		area=(540, 20, 67, 22),
		keyword="",
		name="ticket_count"
	)
	# 999门票数量 
	O_ANIVERSARY_TICKET_COUNT = RuleOcr(
		roi=(910, 20, 126, 22),
		area=(910, 20, 126, 22),
		keyword="",
		name="aniversary_ticket_count"
	)
	# 五倍卷数量 
	O_FIVEFOLD_COUNT = RuleOcr(
		roi=(750, 20, 57, 22),
		area=(750, 20, 57, 22),
		keyword="",
		name="fivefold_count"
	)


