from module.image_processing.rule_image import RuleImage
from module.image_processing.rule_ocr import RuleOcr
from module.image_processing.rule_swipe import RuleSwipe
from module.image_processing.rule_click import RuleClick

# This file was automatically generated by ./module/impage_processing/assets_extractor.py.
# Don't modify it manually.
class DailyBoardAssets: 

	# Image Rule Assets
	# 日常版面页眉 
	I_DAILY_HEADER = RuleImage(
		name="daily_header",
		roi=(610, 70, 56, 31),
		area=(594, 54, 88, 63),
		file="./tasks/components/daily_board/res/daily_header.png"
	)
	# 参加 
	I_EVENT_JOIN = RuleImage(
		name="event_join",
		roi=(547, 360, 48, 35),
		area=(529, 342, 84, 71),
		file="./tasks/components/daily_board/res/event_join.png"
	)
	# 阴界之门logo 
	I_NW_LOGO = RuleImage(
		name="nw_logo",
		roi=(279, 523, 62, 42),
		area=(258, 502, 104, 84),
		file="./tasks/components/daily_board/res/nw_logo.png"
	)
	# 曜 
	I_DAY_CHARACTER = RuleImage(
		name="day_character",
		roi=(224, 427, 27, 28),
		area=(200, 403, 75, 76),
		file="./tasks/components/daily_board/res/day_character.png"
	)


